### ISSUE TITLE
Invalid file permissions for sdluatex in distros

### ISSUE THREAD

**Issue by zopyx** [speedata/publisher#104]
MacBookAirAndreas:examples ajung$ sp
Run speedata publisher
fork/exec /opt/speedata-publisher/sdluatex/sdluatex: permission denied

At least Mac and Linux distros contain the  sdluatex binary without +x flag set.

**Comment by pgundlach** [comment]
speedata-publisher-linux-amd64-2.6.0.zip - confirmed
speedata-publisher-linux-386-2.6.0.zip  - confirmed
speedata-publisher-darwin-amd64-2.6.0.zip - confirmed

so the rest is probably broken as well...  This is not good...
