### ISSUE TITLE
MathML support

### ISSUE THREAD

**Issue by ousia** [speedata/publisher#107]
@pgundlach,

considering _Publisher_ as a replacement for LaTeX to generate PDF documents from `pandoc`, I wonder whether you would be interested in implementing MathML support.

Sorry, I’m not a coder myself. But since ConTeXt has support for MathML itself, maybe it could be adapted from there to _Publisher_ (my apologies, if I’m writing nonsense).

BTW, many thanks for choosing the AGPL 3 as the license.

**Comment by pgundlach** [comment]
MathML support is on the to do list, but not without a sponsor that pays for the implementation. So yes, I am very interested in MathML support (math support in general would be nice). But I will close this ticket, for the implementation will be only done if someone with some money needs it. Thank you anyway for bringing it up.

**Comment by ousia** [comment]
Do you have a public list of features in search of sponsor?

**Comment by pgundlach** [comment]
No, I don't have such a thing. It goes the other way round: someone needs feature X and is willing to pay for its implementation. Then I go ahead and implement it. I have a few things that I'd like to see in the publisher, but not a list as such.
