### ISSUE TITLE
Allow assigning the PDF document metadata properties

### ISSUE THREAD

**Issue by webservant317** [speedata/publisher#148]
Allow assigning the PDF document metadata properties such as title, author, subject, and key words.  Perhaps there is an API to the PDF document properties that would also allow assignment of initial view properties and custom properties.  Also what about font embedding?  Looks like fonts are embedded by default which works for me, but there may be reasons to not embed fonts.

Thanks again for this great software!

**Comment by pgundlach** [comment]
Thanks for the report. For the font embedding: unless there is a technical issue, I'll leave it as it is.  I will have a look at the other topics.
