### ISSUE TITLE
Add <Exit test=''>Exist message</Exit> element to allow conditional exit from execution

### ISSUE THREAD

**Issue by webservant317** [speedata/publisher#149]
In my use case I would like to confirm that the `<Otherwise></Otherwise>` of a case statement is never reached because all valid cases are accounted for in `<Case>`.  So currently I simply call an invalid element within the `<Otherwise><Invalid/></Otherwise>`.  This allows the software to properly execute and if the `<Otherwise>` is ever executed it will stop the execution.  So this works, but it does not properly validate with `sp --filter`.  So perhaps it would be better to create an element specifically designed to exit early with an error message, such as `<Exit test=''>Exist message</Exit>`.

**Comment by pgundlach** [comment]
You can use `<Message select='My error message' error='yes' />` to signal an error. The software will exit with a status != 0 so you can see the error condition from outside.

An <Exit> command would be interesting. It would be something like "finish the PDF file with what you have now and stop the software", right?

**Comment by webservant317** [comment]
Yes the <Message> command is what I was looking for.
However, yes add the option to "finish the PDF file with what you have now
and stop the software"
You would have to decide what to do in the case of multiple runs requested.
In my use case I just what to be able to stop all processing immediately and
print an error.
 
 

  _____
