### ISSUE TITLE
Add option: "Check if all glyphs are available"

### ISSUE THREAD

**Issue by pgundlach** [speedata/publisher#150]
For example if I try to typeset "House" and there is no "H" in the font, there should be an error message or warning. As this will slow down typesetting a bit, it should be an option.

**Comment by webservant317** [comment]
Just noting that when I originally suggested this feature I also suggested that perhaps this should be a fatal error.  However, I have changed my mind.  I am working with a text body that has a rogue Glyph 2303 (hex).  So for now it is handy to be made aware of the fact via the warning you introduced, yet the process successfully completes.  It might be debated whether it would be better for Speedata to require all text to be cleaned up before processing.  However for now it is very convenient for me as is.

**Comment by pgundlach** [comment]
You can remove the error with the command `<Options>`, see https://speedata.github.io/publisher/manual/commands-en/options.html#reportmissingglyphs
