### ISSUE TITLE
Allow specifying PDF metadata using the <Options> element

### ISSUE THREAD

**Issue by webservant317** [speedata/publisher#160]
PDF files allow various metadata including Title, Author, Subject, and Keywords.  Perhaps the <Options> element could be used to make these assignments.

**Comment by pgundlach** [comment]
You can already specify author and title with PDFOptions. See https://speedata.github.io/publisher/manual/commands-en/pdfoptions.html

**Comment by ousia** [comment]
@pgundlach, how about implementing `/Subject` and `/Keywords`?

**Comment by webservant317** [comment]
The complete set of options could be...

Title
Author
Subject
Keywords
Security> many options
Initial View > many options
Custom > many > Name, Value
Advanced > many options

Maybe some of them are easier to add than others.
