### ISSUE TITLE
Missing glyph error reporting a false positive ~ Error: Glyph 14d (hex) and Glyph 113 (hex) is missing from the font "Scheherazade-Bold" 

### ISSUE THREAD

**Issue by webservant317** [speedata/publisher#162]
I am getting the errors..
===
Error: Glyph 14d (hex) is missing from the font "Scheherazade-Bold"
Error: Glyph 113 (hex) is missing from the font "Scheherazade-Bold"
===

However, my data.xml file does not contain these unicodes.  I have privately emailed you my test case environment.  Thanks.

**Comment by pgundlach** [comment]
In the data file you have sent me I can find at least one occurence of `(aiōn)` which contains the glyph 14d (LATIN SMALL LETTER O WITH MACRON) and `Hadēs` which contains 113 (LATIN SMALL LETTER E WITH MACRON)

So I close this issue, if you think that there is really an error here, you can re-open it.

**Comment by webservant317** [comment]
hmmm yes.  I see that now.  Thanks and sorry for the unnecessary work.
