### ISSUE TITLE
<Nobreak reduce="fontsize"> behaviour unpredictable on short lines

### ISSUE THREAD

**Issue by iclukas** [speedata/publisher#177]
Using `<Nobreak reduce="fontsize">` on shorter text yields unpredictable behaviour. Sometimes the text overshoots quite a bit. It seems to depend on lettershapes, font size and width of the `<Textblock>`.

<Layout xmlns="urn:speedata.de:2009/publisher/en" xmlns:sd="urn:speedata:2009/publisher/functions/en">

    <Pageformat width="100mm" height="100mm" />

    <DefineFontfamily name="Text" fontsize="14" leading="14" >
        <Regular fontface="sans"/>
    </DefineFontfamily>

    <Trace gridallocation="yes" grid="yes"/>

    <Record element="data">
        <PlaceObject>
            <Textblock width="5" fontface="Text">
                <Paragraph>
                    <NoBreak reduce="fontsize" factor="0.9">
                        <Value>The quick brown fox jumps over the lazy dog.</Value>
                    </NoBreak>
                </Paragraph>
            </Textblock>
        </PlaceObject>
        <PlaceObject>
            <Textblock width="5" fontface="Text">
                <Paragraph>
                    <NoBreak reduce="fontsize" factor="0.9">
                        <Value>The quick brown fox jumps over.</Value>
                    </NoBreak>
                </Paragraph>
            </Textblock>
        </PlaceObject>
        <PlaceObject>
            <Textblock width="5" fontface="Text">
                <Paragraph>
                    <NoBreak reduce="fontsize" factor="0.9">
                        <Value>The quick brown fox jumps ove.</Value>
                    </NoBreak>
                </Paragraph>
            </Textblock>
        </PlaceObject>
        <PlaceObject>
            <Textblock width="5" fontface="Text">
                <Paragraph>
                    <NoBreak reduce="fontsize" factor="0.9">
                        <Value>The Quick Brown Fox Jumps Ove.</Value>
                    </NoBreak>
                </Paragraph>
            </Textblock>
        </PlaceObject>
        <PlaceObject>
            <Textblock width="5" fontface="Text">
                <Paragraph>
                    <NoBreak reduce="fontsize" factor="0.9">
                        <Value>The quick brown fox jumps ov.</Value>
                    </NoBreak>
                </Paragraph>
            </Textblock>
        </PlaceObject>
        <PlaceObject>
            <Textblock width="5" fontface="Text">
                <Paragraph>
                    <NoBreak reduce="fontsize" factor="0.9">
                        <Value>The Quick Brown Fox Jumps Ov.</Value>
                    </NoBreak>
                </Paragraph>
            </Textblock>
        </PlaceObject>
        <PlaceObject>
            <Textblock width="5" fontface="Text">
                <Paragraph>
                    <NoBreak reduce="fontsize" factor="0.9">
                        <Value>The quick brown fox jumps o.</Value>
                    </NoBreak>
                </Paragraph>
            </Textblock>
        </PlaceObject>
        <PlaceObject>
            <Textblock width="5" fontface="Text">
                <Paragraph>
                    <NoBreak reduce="fontsize" factor="0.9">
                        <Value>The Quick Brown Fox Jumps O.</Value>
                    </NoBreak>
                </Paragraph>
            </Textblock>
        </PlaceObject>
    </Record>

</Layout>

**Comment by pgundlach** [comment]
Ouch... thanks for the report, I'll have a look.

**Comment by iclukas** [comment]
Found it. Will create a PR.
