### ISSUE TITLE
<SetVariable> inside <Pagetype>

### ISSUE THREAD

**Issue by iclukas** [speedata/publisher#184]
`<SetVariable>` would be really handy inside `<Pagetype>` definitions. Right now I’m using a mess like this `column="{(sd:number-of-columns() - 5) div 2 + 5 + 1 + ((sd:number-of-columns() - 5) div 2 - 5) div 2 + 5}"` to have parametric column widths.

**Comment by iclukas** [comment]
After some testing, I think this just works as it should and the restriction is rather artificial. There already exist at least two workarounds: Wrapping `<SetVariable>` with `<ForAll select="1">` (kludgy) and defining the variables just before `<Pagetype>`. But I think it’s just good practice to put variables inside the blocks where you use them.

If you like, I can create a PR.

**Comment by pgundlach** [comment]
I'd be happy to get a PR.

**Comment by iclukas** [comment]
After some more testing, maybe this is not the best idea. E.g. ```<SetVariable variable="x" select="sd:number-of-columns()"/>``` directly beneath ```<PageType>``` will create a new page prematurely and lead to errors. However, it works as expected inside a ```<PositioningArea>```. You can even reference already existing PositioningAreas inside the same PageType.

**Comment by pgundlach** [comment]
So we can close this issue?
