### ISSUE TITLE
Build Instructions missing some details

### ISSUE THREAD

**Issue by luckyhacky** [speedata/publisher#216]
Thanks for the great project.
I tried to compile the project on my own, but failed on different stages.

I tried to compile speedata by using the doc from https://doc.speedata.de/publisher/en/description-en/installation.html:
```
sudo apt install build-essential git rake golang
git clone https://github.com/speedata/publisher.git
cd publisher
rake build
rake buildlib
```

rake build is failing:

> /usr/src/publisher# rake build
> go install -ldflags "-X main.basedir=/usr/src/publisher -s"  sphelper/sphelper
> can't load package: package sphelper/sphelper: cannot find package "sphelper/sphelper" in any of:
>         /usr/lib/go-1.6/src/sphelper/sphelper (from $GOROOT)
>         ($GOPATH not set)
> rake aborted!
> Command failed with status (1): [go install -ldflags "-X main.basedir=/usr/...]
> /usr/src/publisher/Rakefile:50:in `block in <top (required)>'
> Tasks: TOP => build => sphelper
> (See full trace by running task with --trace)

for this GOPATH should be mentioned in install how to

> /usr/src/publisher# export GOPATH=/usr/src/publisher/
> /usr/src/publisher# rake build
> go install -ldflags "-X main.basedir=/usr/src/publisher -s"  sphelper/sphelper
> can't load package: package sphelper/sphelper: cannot find package "sphelper/sphelper" in any of:
>         /usr/lib/go-1.6/src/sphelper/sphelper (from $GOROOT)
>         /usr/src/publisher/src/sphelper/sphelper (from $GOPATH)
> rake aborted!
> Command failed with status (1): [go install -ldflags "-X main.basedir=/usr/...]
> /usr/src/publisher/Rakefile:50:in `block in <top (required)>'
> Tasks: TOP => build => sphelper
> (See full trace by running task with --trace)

The path are also not working:
export GOPATH=/usr/src/publisher/src/
export GOPATH=/usr/src/publisher/src/go/

So there seems to be another issue with it. Maybe you can give advice or post your configuration for golang because it is not mentionend in README or Install

I tried two sysytem configurations:
Ubuntu 16.04.05 LTS - go version go1.6.2 linux/amd64
Ubuntu 18.04.01 LTS - go version go1.10.4 linux/amd64

Maybe you can provide build instructions for clean system with whole setup and extend the docs.

**Comment by pgundlach** [comment]
Thank you. I need to update the instructions. Go >= 1.11 is needed (I've switched to go modules, so setting GOPATH is of no use :(
