### ISSUE TITLE
Fatal error with HSpace at the beginning of a paragraph

### ISSUE THREAD

**Issue by pgundlach** [speedata/publisher#226]
```xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en"
  version="3.6">

  <Record element="data">
    <PlaceObject>
      <Textblock >
        <Paragraph>
          <HSpace/>
          <Value>txt</Value>
        </Paragraph>
      </Textblock>
    </PlaceObject>
  </Record>
</Layout>
```

gives `Assertion failed: (vlink(o)==cur_p), function ext_try_break, file ../../../texk/web2c/luatexdir/tex/linebreak.w, line 1271.` and a fatal error.

**Comment by poetaman** [comment]
@pgundlach I wonder what all is not permitted in beginning? In my testing (unrelated to speedata*), a disc node (with penalty:50) in the beginning of nodelist fed to `tex.linebreak` also results in the same error. I reached your page while searching for any information on this same error, and this is the only hit I got.

**Comment by pgundlach** [comment]
@reportaman I can't tell you more. Someone has found this bug and I tracked it down that the hspace was at the beginning, but that is about all I know....

**Comment by poetaman** [comment]
Sure, I'll write a test program, and post it on tex.SE, or at least first ask that question there :)

**Comment by poetaman** [comment]
@pgundlach Btw, in my case, adding a local_par node in the very beginning (before disc with penalty) resolved this error. I wonder if that's it, and would cover all cases... In that case, its cleaner than having to check the id's and sequences of id's that hit this error.
