### ISSUE TITLE
Image not found issues

### ISSUE THREAD

**Issue by iclukas** [speedata/publisher#241]
I ran into two issues here:
* Missing intermediate certs make images from https sources non-readable. The same is probably true for invalid certs.
* If the current user (running sp) has no write permissions to the IMGCACHE dir, an „Image not found!“ error is issued.

In both cases the error messages are very misleading. Clearer messages would have saved me several hours of debugging.

In the first case, I’m not really sure why the cert error is not being displayed.

In the second case, it seems like ```saveFileFromUrl()``` doesn’t properly output the error because the path exists and leads to a dir. It’s just not writeable. Not sure if ```MkDirAll()``` returns an error, but it wouldn’t be handled anyway.

**Comment by pgundlach** [comment]
Actually the cert error is displayed, but totally out of sync (and I think it is not in the log file, so it is rather useless). I'll fix this by returning an error value and check for it.

I am not sure how to properly fix the second issue though. I will honor the error value from mkdir and now return all error values, so hopefully all things that can go wrong are now in the log file.

**Comment by pgundlach** [comment]
Thank you very much for the report. A new version of the publisher is now available for download (3.7.17).
