### ISSUE TITLE
module 'Box' not found:

### ISSUE THREAD

**Issue by michal-h21** [speedata/publisher#252]
Hi,

I am trying the `html` subcommand from the latest development version (3.9.11), with the sample file from [your blog post](https://blog.speedata.de/2020/05/12/print-css-speedata/):

```
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link href="styles.css" rel="stylesheet">
</head>
<body>
    <h1>Header 1</h1>
    <p>Text im Absatz</p>
</body>
</html>

```

It fails with the following error message: 

       /home/mint/prg/speedata-publisher/sw/lua/publisher/html.lua:12: module 'Box' not found

I've found that there is a `box.lua` module in `sw/lua` directory, so I guess it is a typo in `html.lua` and the required module should be `box` instead.

**Comment by pgundlach** [comment]
I guess I should not develop on a case insensitive file system... I'll upload a fix when I test it (tomorrow) 

Thank you very much for the report.
