### ISSUE TITLE
readlink /proc/self/exe: no such file or directory

### ISSUE THREAD

**Issue by mrdonthave** [speedata/publisher#254]
Hi,

unfortunately i have no experience in GOLANG.
On my desktop computer and on my vServer the publisher runs fine. But if i try to run on a ssh-enabled shared hosting i've got the error "readlink /proc/self/exe: no such file or directory" when try to run.

Is there any possibility to run the publisher even in environments /proc is not available? I've read an article (https://github.com/takama/daemon/issues/64). Would such thing making sense?

The availability of the publisher would be raised, i think.

**Comment by pgundlach** [comment]
Thank you very much for your bug report and your analysis! Very helpful.

Unfortunately I can't reproduce this myself, so I need help to check if my fix solves the problem. Would it be possible for you to try out the version 3.9.13 now available at <https://download.speedata.de>? I have applied the changes you have linked to.

**Comment by pgundlach** [comment]
The new version 3.9.13 should work now.
