### ISSUE TITLE
Underline does not change color

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#256]
Hello,

I have the below code:

`<Color name="red"><U><Value select="'TITLE'"/></U></Color>`

The result is, the word TITLE is red, but the underline beneath it is black.
Is this a bug? Or is there any other way of changing the color of the underline?

**Comment by pgundlach** [comment]
> This looks like a bug. I am currently offline and unable to fix,but I’ll look into it as soon as possible 

Thank you for the report!

**Comment by pgundlach** [comment]
Thanks again for the report. The fixes are now in version 3.9.25, available for download (https://download.speedata.de)
