### ISSUE TITLE
Layout Schema - possible changes

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#257]
Hi, 

I was validating a layout file according to the layout schema and there are some errors of elements not allowed in specific parents.
But ignoring these errors and publishing outputs the PDF correctly and with the desired behavior.
So, I was wondering if you could edit the layout schema to allow these elements in the corresponding parents, as long as this doesn't cause problems elsewhere, and as long as using them like this leads to the desired behavior.

The changes I think could be made are:
- Loop to allow Color as child
- Tablehead to allow ForAll as child. 
- A to allow HSpace as child. I used this to create a TOC where the dots are also clickable as links.

**Comment by pgundlach** [comment]
I will add this next week, when I am back from vacation. Thank you for the report!
