### ISSUE TITLE
xi:include doesn't work inside table td

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#263]
Inside a table td, xi:include doesn't seem to work.
See attached zip.

If I put the content from the second layout in the first one, it works.
Is there any reason why the xi:include doesn't work inside td ?

[XIinclude.zip](https://github.com/speedata/publisher/files/5223682/XIinclude.zip)

**Comment by pgundlach** [comment]
In some sense it seems to work, but the table does not like the root element of the layout file. This needs to be fixed.

**Comment by pgundlach** [comment]
A fix will be in version 4.1.3 to be released soon.
