### ISSUE TITLE
padding-right not working for paragraph

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#267]
Hi, 

I think the padding-right attribute doesn't work as it should for paragraph. 

![padding-right](https://user-images.githubusercontent.com/68335318/95052157-bdba0500-06ee-11eb-9276-2e38ea1194ed.jpg)

[padding-right.zip](https://github.com/speedata/publisher/files/5325894/padding-right.zip)

**Comment by pgundlach** [comment]
Fixed in 4.1.6 (now online). Thank you for the bug report!
