### ISSUE TITLE
Centered alignment broken inside table td in version 4.1.7

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#270]
Hi,

In the latest version 4.1.7, the center alignment seems to not work inside table td.
In 4.1.6. this worked.

Edit: Could be that all instructions from the textformat are ignored. Now I see that the padding-top and Margin-top are also not applied.

[centeredText.zip](https://github.com/speedata/publisher/files/5363725/centeredText.zip)

**Comment by pgundlach** [comment]
Thanks again for the bug report. The fix is now in the current speedata Publisher download (4.1.8).
