### ISSUE TITLE
Memory Limitation on Windows 10 64bit

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#272]
Hi,

Some time ago I asked you about some memory errors I was getting on Windows 10 64bit.
Since then I have been trying to optimize my layout in order to increase the number of pages I can print under Windows.
Initially I was able to print only around 300 pages, now I have raised that number to 2500.

Steps I have taken to optimize my layouts:
1. Split the layout in smaller layouts using xi:include. Before I had one big layout.
2. Reduce the number of variables. Before, I was "abusing" the use of variables.
3. Reduce the size of content I save in variables (For example variables used to create indexes).
4. Split big data files in smaller chunks.
5. Split indexes in smaller chunks.

All these managed to increase the maximum number of page until 2500 under windows. But this is still not enough. Under Linux inside VirtualBox I am able to print more than 10000 pages using the exact same layout and setup.

So obviously there is also a problem with the binaries for Windows that is causing this memory limit.
As you said, the reason might be due to the fact that the binaries for Windows are for 32bit, as stated in this article also: [https://tex.stackexchange.com/questions/373392/error-lua-not-enough-memory?newreg=6758e1eabf2f4b9b9f2bd32102a0fa0d](url)

So, if possible, can you please create Windows binaries for 64bit also?

**Comment by Demosteneus** [comment]
Additionally, do you think it would be possible to create a feature to delete variables after using them?
I have been trying to set them no nothing after using them, but this didn't seem to have any effect.
Completely deleting variables could be a great improvement.

**Comment by pgundlach** [comment]
I can't find easy to install / supply 64 bit binaries for luajithbtex. 

For the second part: deleting variable will be only one part of the game, I would need to free the internal data structures as well, since there is no garbage collection.

Getting less memory usage on Windows is not an easy task. If someone would sponsor the time, I could try to make 64 bit binaries and look into making proper variable deletion.

I agree that this is an issue, but not easy to solve.

**Comment by pgundlach** [comment]
@Demosteneus I have added a 64bit windows binary. Could you try that?

https://download.speedata.de/

**Comment by Demosteneus** [comment]
Hello,

I tried it out and at first look I can see an improvement. 
With the 32bit version  I was able to print at most 3600 pages on Windows.
With the new 64 bit I already printed a 5400 pages document.

**Comment by pgundlach** [comment]
OK, at least *some* progress... Thanks

**Comment by Demosteneus** [comment]
Some updates:

I have tried to print double what I was able before (5400) and it was failing with the same error message: "not enough memory".
Step by step I reduced the size in order to find where the limit is. And I think is around 9800 pages.
This is still a bit lower what I can print on Linux inside a virtual machine (11000 pages)

I don't really have a problem anymore with this limitation, as I don't really need such big number of pages.
But I have a problem with this error message "not enough memory", which if I am not mistaken comes from LuaTeX, right?
But according to this document https://www.tug.org/texlive//devsrc/Master/texmf-dist/doc/context/documents/general/manuals/luatex.pdf

"‘Out of main memory’ errors can still occur, but the limiting factor is now the amount of RAM in your system, not a predefined limit."

But this really cannot be the case, since I have 32 GB RAM, and the usage of sdluatex.exe never goes above 2 GB.

**Comment by Demosteneus** [comment]
Hi, 

I cannot find the Windows x64bit version anymore.
Will you create x64bit for the newer releases?

**Comment by pgundlach** [comment]
Yes.

I need to set up the build machine for w64 bit. The previous version was just a test.

**Comment by pgundlach** [comment]
New stable is still 32 bit, last development and future development versions will be 64 bit. I close this issue. If there is further action required, please create a new new issue.
