### ISSUE TITLE
<Intial> glyph placement / leading encroaches on surrounding text with mode=harfbuzz, bidi=yes direction=rtl

### ISSUE THREAD

**Issue by webservant316** [speedata/publisher#287]
See page #1, Hebrew example at http://stageresources.aionianbible.org/AB-RTL-TESTS/output-2020-12-16.pdf
See layout.xml at http://stageresources.aionianbible.org/AB-RTL-TESTS/input-2020-12-16.xml
See configurations at http://stageresources.aionianbible.org/AB-RTL-TESTS

Worse examples also observed in my production environment

**Comment by pgundlach** [comment]
Could you please make a short test file for the problem? I have all fonts here, I just need the data and input.

**Comment by webservant316** [comment]
[data.xml.txt](https://github.com/speedata/publisher/files/5713398/data.xml.txt)
[input-rtl-initial-leading.xml.txt](https://github.com/speedata/publisher/files/5713399/input-rtl-initial-leading.xml.txt)

**Comment by pgundlach** [comment]
I can't see what is wrong and what you'd expect instead. Perhaps a picture might help?

**Comment by webservant316** [comment]
See failed use of <Initial> in attached PDF.  See the glyph in the <Initial> overlaps surrounding text below the <Initial>

[Pages from Holy-Bible---Arabic---Arabic-Van-Dyck-Bible---Aionian-Edition.pdf](https://github.com/speedata/publisher/files/5716797/Pages.from.Holy-Bible---Arabic---Arabic-Van-Dyck-Bible---Aionian-Edition.pdf)

Had trouble illustrating with a small example to produce same effect.  However, my entire package for produce the PDF documents is found at 

http://stageresources.aionianbible.org/Holy-Bible---Arabic---Arabic-Van-Dyck-Bible---SPEEDATA.zip

**Comment by pgundlach** [comment]
Initial placement is pure luck currently in speedata. 

layout:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Layout xmlns="urn:speedata.de:2009/publisher/en" xmlns:sd="urn:speedata:2009/publisher/functions/en">
	<LoadFontfile mode="harfbuzz" name="amiri" filename="amiri-regular.ttf" />

	<DefineFontfamily name="text" fontsize="10" leading="12">
		<Regular fontface="amiri" />
	</DefineFontfamily>

	<DefineFontfamily name="init" fontsize="24" leading="24">
		<Regular fontface="amiri" />
	</DefineFontfamily>

	<!-- DEFINE PAGES -->
	<SetGrid width="4.5pt" height="4.5pt" />

	<Pagetype name="t" test="true()">
		<Margin left="0.25in" right="0.25in" top="0.25in" bottom="0.25in" />
		<PositioningArea name="area2col">
			<PositioningFrame row="1" column="1" width="43" height="132" />
			<PositioningFrame row="1" column="46" width="43" height="132" />
		</PositioningArea>
	</Pagetype>


	<!-- PRINT CHAPTER -->
	<Record element="chapter">
		<Output area="area2col">
			<Text>
				<Paragraph language='Other' bidi="yes" direction="rtl">
					<Initial fontfamily="init" padding-right="2pt">
						<Value>١</Value>
					</Initial>
					<Value select="." />
				</Paragraph>
			</Text>
		</Output>
	</Record>
</Layout>
```

```xml
<?xml version='1.0' encoding='utf-8'?>
<chapter CHAP='١'>
    <span class='vn' V='1' VN='١'> ١</span>
    <span class='v'>فِي ٱلْبَدْءِ خَلَقَ ٱللهُ ٱلسَّمَاوَاتِ وَٱلْأَرْضَ.</span>
    <span class='vn' V='2' VN='٢'> ٢</span>
    <span class='v'>وَكَانَتِ ٱلْأَرْضُ خَرِبَةً وَخَالِيَةً، وَعَلَى وَجْهِ ٱلْغَمْرِ ظُلْمَةٌ، وَرُوحُ ٱللهِ يَرِفُّ عَلَى وَجْهِ ٱلْمِيَاهِ.</span>
    <span class='vn' V='3' VN='٣'> ٣</span>
    <span class='v'>وَقَالَ ٱللهُ: «لِيَكُنْ نُورٌ»، فَكَانَ نُورٌ.</span>
    <span class='vn' V='4' VN='٤'> ٤</span>
    <span class='v'>وَرَأَى ٱللهُ ٱلنُّورَ أَنَّهُ حَسَنٌ.  وَفَصَلَ ٱللهُ بَيْنَ ٱلنُّورِ وَٱلظُّلْمَةِ.</span>
    <span class='vn' V='5' VN='٥'> ٥</span>
    <span class='v'>وَدَعَا ٱللهُ ٱلنُّورَ نَهَارًا، وَٱلظُّلْمَةُ دَعَاهَا لَيْلًا.  وَكَانَ مَسَاءٌ وَكَانَ صَبَاحٌ يَوْمًا وَاحِدًا.</span>
    <span class='vn' V='6' VN='٦'> ٦</span>
    <span class='v'>وَقَالَ ٱللهُ: «لِيَكُنْ جَلَدٌ فِي وَسَطِ ٱلْمِيَاهِ.  وَلْيَكُنْ فَاصِلًا بَيْنَ مِيَاهٍ وَمِيَاهٍ».</span>
</chapter>
```


<img width="421" alt="init" src="https://user-images.githubusercontent.com/209434/102656663-834ff800-4174-11eb-96dd-538d0aa28adb.png">


4.1.23

**Comment by pgundlach** [comment]
Version 4.1.25 will have this fixed (and more control over padding-top and padding-bottom). This is a non-backward compatible change and will change the appearance of all initials - so please double check that you get the desired output.

The old implementation was just crap and needed a complete rewrite (nothing big, just a different way to move the initial around and to calculate the line height).

<img width="597" alt="initial" src="https://user-images.githubusercontent.com/209434/103782909-5a66a880-5038-11eb-8a4a-43141d66c375.png">

Thank you as always for the example, the bug report and your patience.
