### ISSUE TITLE
Why does direction=rtl reverse the order of english LTR phrases when bidi=yes?

### ISSUE THREAD

**Issue by webservant316** [speedata/publisher#288]
See page #2, English phrase example at http://stageresources.aionianbible.org/AB-RTL-TESTS/output-2020-12-16.pdf
See page #3, Smart quote example at http://stageresources.aionianbible.org/AB-RTL-TESTS/output-2020-12-16.pdf
See layout.xml at http://stageresources.aionianbible.org/AB-RTL-TESTS/input-2020-12-16.xml
See configurations at http://stageresources.aionianbible.org/AB-RTL-TESTS

**Comment by pgundlach** [comment]
Could you please make a short test file for the problem? I have all fonts here, I just need the data and input.

**Comment by webservant316** [comment]
[data.xml.txt](https://github.com/speedata/publisher/files/5713394/data.xml.txt)
[input-rtl-reverses-ltr.xml.txt](https://github.com/speedata/publisher/files/5713395/input-rtl-reverses-ltr.xml.txt)

**Comment by pgundlach** [comment]
That is the way it is supposed to be. See [this fiddle](https://jsfiddle.net/prt2L35c/).
