### ISSUE TITLE
The attribbute direction=rtl wrongfully impacts layout spacing

### ISSUE THREAD

**Issue by webservant316** [speedata/publisher#289]
See page #4, layout example at http://stageresources.aionianbible.org/AB-RTL-TESTS/output-2020-12-16.pdf
See layout.xml at http://stageresources.aionianbible.org/AB-RTL-TESTS/input-2020-12-16.xml
See configurations at http://stageresources.aionianbible.org/AB-RTL-TESTS

The page #4 layout example has three blocks of very similar layout each with an intentional whitespace.  Notice that in the 3rd block the whitespace is larger and the only difference is that the attribute direction=rtl is added.

**Comment by pgundlach** [comment]
Could you please make a short test file for the problem? I have all fonts here, I just need the data and input.

**Comment by webservant316** [comment]
[data.xml.txt](https://github.com/speedata/publisher/files/5713392/data.xml.txt)
[input-rtl-layout-spacing.xml.txt](https://github.com/speedata/publisher/files/5713393/input-rtl-layout-spacing.xml.txt)

**Comment by pgundlach** [comment]
A slightly shorter example showing the problem:

<img width="494" alt="vspace" src="https://user-images.githubusercontent.com/209434/102576269-67f1d800-40f5-11eb-9e4c-1aaaa8109bba.png">

`layout.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Layout xmlns="urn:speedata.de:2009/publisher/en" xmlns:sd="urn:speedata:2009/publisher/functions/en">
	<Trace grid="yes" />

	<DefineFontfamily name="FF-Tiny" fontsize="5" leading="5">
		<Regular fontface="sans" />
	</DefineFontfamily>

	<SetGrid nx="2" height="15pt" />
	<Pageformat width="5cm" height="4cm" />

	<Record element="data">
		<PlaceObject>
			<Textblock width="1">
				<Paragraph language="Other" textformat="left" bidi="yes">
					<Value>A</Value>
					<Br />
					<Fontface fontfamily='FF-Tiny'>
						<Br />
					</Fontface>
					<Value>B</Value>
				</Paragraph>
			</Textblock>
		</PlaceObject>
		<PlaceObject>
			<Textblock width="1">
				<Paragraph language="Other" textformat="left" bidi="yes" direction="rtl">
					<Value>C</Value>
					<Br />
					<Fontface fontfamily='FF-Tiny'>
						<Br />
					</Fontface>
					<Value>D</Value>
				</Paragraph>
			</Textblock>
		</PlaceObject>
	</Record>
</Layout>
```

`data.xml`:

    <data />

**Comment by pgundlach** [comment]
Somehow “Adjust line heights” seems to behave differently. `<br>` should separate the line height adjustment.
