### ISSUE TITLE
Boomark Issues

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#290]
Hi,

I  noticed some issues with the Bookmark element:

1. In the Speedata manual there is some discrepancy between these 2 pages:

https://doc.speedata.de/publisher/en/commandreference/bookmark/

https://doc.speedata.de/publisher/en/advancedtopics/bookmarks/#ch-bookmarks

On the first page it says that Bookmark can be added in these parents:  "AtPageCreation, AtPageShipout, Case, Contents, ForAll, While"
On the second page there is an example of Bookmark usage where it is added inside a PlaceObject.

2. I have added a Bookmark inside a PlaceObject similar to the example from the second page from above, as follows:

2.1. When the Bookmark is added inside PlaceObject above Textblock the publishing fails with error: "Error: [page 1] Something is wrong with PlaceObject, content is missing"

2.2. When the Bookmark is added inside PlaceObject bellow Textblock the publishing works.

data.xml:
```
<test>
</test>
```

This fails:

```
<Layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="layoutschema-en.xsd" xmlns:sd="urn:speedata:2009/publisher/functions/en" xmlns="urn:speedata.de:2009/publisher/en" xmlns:xi="http://www.w3.org/2001/XInclude" version="4.1.23">
	<DefineColor name="blue" model="RGB" r="0" g="0" b="255"/>
	<Record element="test">
		<PlaceObject column="10" row="24">
			<Bookmark select="'Bookmark 2'" level="1"/>
			<Textblock>
				<Paragraph>
					<Value>Destination</Value>
					<Action>
						<Mark select="'destination'" pdftarget="yes"/>
					</Action>
				</Paragraph>
			</Textblock>
		</PlaceObject>
	</Record>
</Layout>
```

This works:

```
<Layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="layoutschema-en.xsd" xmlns:sd="urn:speedata:2009/publisher/functions/en" xmlns="urn:speedata.de:2009/publisher/en" xmlns:xi="http://www.w3.org/2001/XInclude" version="4.1.23">
	<DefineColor name="blue" model="RGB" r="0" g="0" b="255"/>
	<Record element="test">
		<PlaceObject column="10" row="24">
			<Textblock>
				<Paragraph>
					<Value>Destination</Value>
					<Action>
						<Mark select="'destination'" pdftarget="yes"/>
					</Action>
				</Paragraph>
			</Textblock>
			<Bookmark select="'Bookmark 2'" level="1"/>
		</PlaceObject>
	</Record>
</Layout>
```

**Comment by pgundlach** [comment]
Thank you for the bug report. It will be fixed in the next release. Bookmark will work directly within the PlaceObject as written in the manual (second link).
