### ISSUE TITLE
Underline Bug

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#291]
Hi,

The underline element "U" fails to underline completely a concatenated string that contains dash "-".

data.xml:
```
<test>
</test>
```

layout.xml:
```
<Layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="layoutschema-en.xsd" xmlns:sd="urn:speedata:2009/publisher/functions/en" xmlns="urn:speedata.de:2009/publisher/en" xmlns:xi="http://www.w3.org/2001/XInclude" version="4.1.23">
	<Record element="test">
		<PlaceObject column="10" row="24">
			<Textblock>
				<Paragraph>
					<U><Value select="concat('Test ', ' - ', 'Underlined Title')"/></U>
				</Paragraph>
			</Textblock>
		</PlaceObject>
	</Record>
</Layout>
```

Output:
![image](https://user-images.githubusercontent.com/68335318/102470029-c5354d00-4053-11eb-82a6-c672aab0c57f.png)

Expected output:
![image](https://user-images.githubusercontent.com/68335318/102470101-daaa7700-4053-11eb-93bf-30dc9726f4e9.png)

**Comment by pgundlach** [comment]
Thank you for the bug report. It will be fixed in the next release.
