### ISSUE TITLE
Moving from version 4.1.25 to 4.3.1 resulted in changes to glyph placement in harfbuzz font text

### ISSUE THREAD

**Issue by Nainoia-Inc-Admin** [speedata/publisher#307]
Notice the placement of the dots in the first example.  Actually the 4.1.25 example is a PDF diff file with the blue dots equal to 4.1.25 placement and the red dots equal to 4.3.1 placement.

[Example of Tamil glyph placement with version 4.1.25.pdf](https://github.com/speedata/publisher/files/5826703/Example.of.Tamil.glyph.placement.with.version.4.1.25.pdf)

Now notice the placement of the dots in the 4.3.1 example.

[Example of Tamil glyph placement with version 4.3.1.pdf](https://github.com/speedata/publisher/files/5826704/Example.of.Tamil.glyph.placement.with.version.4.3.1.pdf)

The 4.3.1 example actually seems better.  However, I was not expecting any change from the changelog changes reported.

Other Hindic and other Harfbuzz languages are also subtly impacted.  See the Arabic, Telugu, and Urdu examples below as well.  Again the attachments below are diffs with the 4.1.25 placement diff in blue and the 4.3.1 placement diff in red.

[Example of Arabic glyph placement with version 4.3.1.pdf](https://github.com/speedata/publisher/files/5826760/Example.of.Arabic.glyph.placement.with.version.4.3.1.pdf)

[Example of Telugu glyph placement with version 4.3.1.pdf](https://github.com/speedata/publisher/files/5826747/Example.of.Telugu.glyph.placement.with.version.4.3.1.pdf)

[Example of Urdu glyph placement with version 4.3.1.pdf](https://github.com/speedata/publisher/files/5826748/Example.of.Urdu.glyph.placement.with.version.4.3.1.pdf)

ALSO note that these is subtle shifts in glyph placement in non-harbuzz languages as well.  See the PDF diff of Chinese glyphs in the caption below the image below....

[Example of Subtle Chinese glyph placement shift with version 4.3.1.pdf](https://github.com/speedata/publisher/files/5826777/Example.of.Subtle.Chinese.glyph.placement.shift.with.version.4.3.1.pdf)

Unfortunately I do not know these languages to say which is correct.  However, my question for now is are these changes expected between 4.1.25 and 4.3.1?

**Comment by pgundlach** [comment]
I don't know anything about these writing systems, but at least the Telugu looks incorrect to me. I need to check with the input.

There are expected accent changes (see #298 and #296). I assume in Telugu I get the direction setting wrong.

For the Chinese example: There are some expected changes, but I don't know what is good and what is bad. So this is not fixed (in the sense that it might change again in the future).

**Comment by pgundlach** [comment]
Looking at the diff PDF for Telugu: I get correct output for Telugu in 4.3.1  which is what in the diff pdf is marked blue. The red marks are not correct.

**Comment by Nainoia-Inc-Admin** [comment]
I completed a full test of my PDF inventory and the glyph accents were placed slightly different in 4.3.2 as well when compared with 4.1.25 as mentioned.  And of course this was only observed in harfbuzz related fonts and languages.  The languages impacted in my environment where Arabic, Assamese, Bengali, Gujarati, Hindi, Marathi, Myanmar, Oriya, Punjabi, Tamil, Telugu, and Urdu.  I will try again to get my Hindic language proofreader moving.  I cannot say whether the changes are for the better or worse.

One more thing.  You mentioned that you adjusted the accent placement to be more accurate for RTL languages. But then why where the accents also changed for harfbuzz Hindic languages that are not RTL?  Is it possible that your adjustment for RTL languages also impacted harfbuzz LTR languages?

**Comment by pgundlach** [comment]
The fix is for LTR and RTL languages when the direction is not set explicitly.

I think this issue should be closed and new issues should be opened once you encounter problems with a specific language.
