### ISSUE TITLE
Path containg Greek letters

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#310]
Hi,

I have my windows system set to English, so I had no problem until now.
But recently I sent a speedata installation to a colleague and he couldn't run the executable sp.exe. 
He was getting an error: " Can't determine where the executable sdluatex.exe is". 
![2021-01-29_100030](https://user-images.githubusercontent.com/68335318/106456852-6191a280-648e-11eb-813a-317a58afce4d.jpg)

After checking, we saw that the sdlutex executable was where it supposed to be.
Then we realized that the problem might be with his username being in Greek.
So, when he put the sp_win folder directly in his 'C:\' directory, it worked.

So, obviously there is an issue with the Greek letters in the windows path.
Do you know if there is something we need to setup in order to work with Greek letters?

**Comment by pgundlach** [comment]
It should work, so this must be a bug.

**Comment by pgundlach** [comment]
The message is generated by LuaTeX. Perhaps I need to change the way LuaTeX is called. Or this is a LuaTeX issue.

**Comment by pgundlach** [comment]
This is a LuaTeX issue. The binary will now start (it gives a different error message), but it cannot find any of the Lua packages. The speedata Publisher will issue a warning in this environment.

**Comment by pgundlach** [comment]
I can't fix this. I have built in a warning with a link to this issue and eventually Lua, LuaTeX or Windows will be fixed...
