### ISSUE TITLE
Numbered lists in html-text - start at property

### ISSUE THREAD

**Issue by b0b23** [speedata/publisher#311]
Let's say your markdown compatible text is as as follow:

`3. Teilrechnung/Schlussrechnung: Relaunch`

after it is run through a markdown parser it gets converted to following:

```
<ol start="3">
<li>Teilrechnung/Schlussrechnung: Relaunch</li>
</ol>
```

it doesn't matter that the text is really, I wanted just to point out - if you create a "numbered list" which doesn't start at "1", the output of speedata will print the list starting at "1".

So the property "start" for OL doesn't seem to be implemented yet

**Comment by pgundlach** [comment]
This is not implemented yet, correct. I will update the documentation. The whole HTML/CSS topic is sparsely covered yet.
