### ISSUE TITLE
PDF Javascript forms?

### ISSUE THREAD

**Issue by Nainoia-Inc-Admin** [speedata/publisher#312]
Does Speedata support creation of PDF form field objects that include associated javascript response?  I am guessing it doesn't because could find anything in the docs.  Are you aware of any programmatic PDF creation tool that does?

**Comment by pgundlach** [comment]
The speedata publisher could inject JS into the PDF, but this is not implemented yet. The only tool that I am aware of, is Adobe Acrobat (not programmatic, of course).

(I assume you know that only a few PDF readers can handle interactive widgets and javascript)

**Comment by Nainoia-Inc-Admin** [comment]
ok thanks.  Just checking.  Yes probably not going this direction.
