### ISSUE TITLE
Feature Request - Override Text Alignment in same paragraph

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#314]
Hi,

I am trying to achieve having in the same paragraph the first part aligned to left and then another part aligned to right. 
Ex:
Left Aligned Text                                       Right Aligned Text

I need this to be inside paragraph because I need it inside tables (I know this might be able to achieve with other commands).

Some ideas I had:
1. An override tag for text format, similarly as there is for font family the Fontface tag. But not sure if this is feasible.
2. An attribute for paragraph to make it possible for a second paragraph to not go automatically on a new line.
3. An attribute for paragraph like label-left, but for the right side, so label-right. But this might not be what I actually need, because I tested label left, and the label was printed outside the limits of the table.

Or do you know any other way of achieving having two alignments in the same paragraph?

**Comment by pgundlach** [comment]
Within one line?

Have you tried hspace? (This does not center the text though)

You could try to next a Table inside Td, but then you need to supply a table width.

**Comment by Demosteneus** [comment]
Thanks, hspace worked. 
The reason I didn't even consider hspace in the first place was because I just checked this command two days ago, in a different context, and it was not working for me. But in that case I was needing hspace with  a specified width and this is what was not working. 
I am trying to reproduce my case with space and a width on a smaller example but it seems to work on smaller examples.
So this issue can be closed.
