### ISSUE TITLE
Hyphenation - no split between minus and numbers

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#322]
Hi,

I have an issue with the way some text is split/hyphenated.
I have some negative values written in brackets, an for some reason when such a value is close to the right side of the page, the value is split like below:
![image](https://user-images.githubusercontent.com/68335318/110481908-5f071600-80e8-11eb-9b39-54c38c9c3ef9.png)

Is it possible to disable such behavior?
I have tried with a textformat that has hyphenate="no" , but this didn't work. Is there any way to avoid splitting text where a "-" is found?

data.xml
`<test></test>`

layout.xml
```
<Layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="layoutschema-en.xsd" xmlns:sd="urn:speedata:2009/publisher/functions/en" xmlns="urn:speedata.de:2009/publisher/en" xmlns:xi="http://www.w3.org/2001/XInclude" version="4.3.8">
    <DefineTextformat name="notHyphenated" alignment="leftaligned" hyphenate="no" />    
    <Record element="test">
        <PlaceObject>
            <Table width="170mm">
                <Columns>
                    <Column width="4mm" />
                    <Column width="166mm" /> 
                </Columns>
                <Tr>
                    <Td/>
                    <Td>
                        <Paragraph textformat="notHyphenated">
                            <Value select="'This example should not be hyphenated, it is a negative value, written inside brackets, so it is no hyphen (-2915) is a negative value that should be printed together with the minus sign.'" />
                        </Paragraph>
                    </Td>
                </Tr>				
            </Table>
        </PlaceObject>
    </Record>
</Layout>
```

**Comment by pgundlach** [comment]
You can use `allowbreak=" "` on the `<Paragraph>`, but that disables hyphenation altogether. 

The speedata Publisher could be extended to handle something like `&#131;` between the - and the number or it should be set up not to insert a hyphenation point between the minus sign of a number.

**Comment by Demosteneus** [comment]
Thanks, for now, allowbreak=" " worked. I think I knew about this solution, but I just forgotten about it.

But indeed, it is a good idea to have support for `&#131;` or to not split between minus and numbers. Maybe this can stay open as a feature request.

**Comment by pgundlach** [comment]
There is the following possibility:

```xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
    xmlns:sd="urn:speedata:2009/publisher/functions/en">
    <Pageformat height="4cm" width="7cm" />
    <Record element="data">
        <PlaceObject>
            <Textblock width="5">
                <Paragraph>
                    <Value>The quick brown fox jumps (&#x2011;1234) over the lazy dog.</Value>
                </Paragraph>
            </Textblock>
        </PlaceObject>
    </Record>
</Layout>
```

which results in 

<img width="231" alt="non-breaking-hyphen" src="https://user-images.githubusercontent.com/209434/165787351-7b40e12d-79d5-48bb-9a7d-a7ec7ea0fee4.png">

So this works as intended.  (Sorry for the late reply, I am currently preparing a new release and look through old issues)
