### ISSUE TITLE
Alphanumeric sort - letters before numbers

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#323]
This is only a feature request.
I see that by default the sorting using SortSequence is done alphabetically as bellow:
1
2
3
a
b
c

Would it be possible to add another mode, to sort letters before numbers?
a
b
c
1
2
3

**Comment by pgundlach** [comment]
I usually sort the entries with XSLT wherever possible, because it has much more control over the sort order. I need to take a look again how it is done there so I can take that design for speedata.

**Comment by pgundlach** [comment]
I'll close this stale feature request (but thank you anyway). If there is commercial need, I'd be happy to get a sponsor for this.
