### ISSUE TITLE
Fatal error with HSpace at the beginning of a paragraph

### ISSUE THREAD

**Issue by langmic** [speedata/publisher#338]
see also #226

layout:
```xml
<Layout xmlns="urn:speedata.de:2009/publisher/en" xmlns:sd="urn:speedata:2009/publisher/functions/en">
  <Record element="data">
    <PlaceObject>
      <Textblock >
        <Paragraph>
          <HSpace/>
          <Value>txt</Value>
        </Paragraph>
      </Textblock>
    </PlaceObject>
  </Record>
</Layout>
```

no issue with version 4.0.1

leads to an assertion with versions 4.2.0 upto 4.5.3

`sdluatex: ../../../texk/web2c/luatexdir/tex/linebreak.c:1529: ext_try_break: Assertion ``varmem[(o)].hh.v.RH == cur_p`` failed.`

Kind Regards, Michael

**Comment by pgundlach** [comment]
Thanks again for the bug report. This time I have added a sample file, so the fix should not get lost the next time when decide to re-write the whole paragraph builder.

**Comment by pgundlach** [comment]
Version 4.5.4 is online now
