### ISSUE TITLE
Layout and data namespace issue on Windows

### ISSUE THREAD

**Issue by dnyamy** [speedata/publisher#343]
Hello,

I have just discovered speedata and I am trying to use it on Windows with following command : 

`sp --data="F:\CPH Edition de Livres\Traitement de livres CPH-ELC\Speeddata publisher\data\data.xml" --layout="F:\CPH Edition de Livres\Traitement de livres CPH-ELC\Speeddata publisher\layout\layout.xml"`

But I am getting following error :

`Error: [page 1] open : Le fichier spécifié est introuvable.`
`Error: [page 1] Cannot find the namespace of the layout file. What should I do?`
`Stop processing data`
`2 errors occurred`

Please how should I specify my own data and layout files ?

Regards
Dn

**Comment by pgundlach** [comment]
Can you pot the first two lines of of the layout xml file? 

It should be like 

```
<Layout
  xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en">

```

**Comment by dnyamy** [comment]
Hello,
Here are the 2 lines 
`<Layout`
`   xmlns="urn:speedata.de:2009/publisher/en"`
`   xmlns:sd="urn:speedata:2009/publisher/functions/en"`

I get no error if I put data and layout files on default location and just call sp wihtout parameters. The issue comes when trying to specify custom paths. And yes I have checked that the paths exist. 

Regards 
Dn

**Comment by pgundlach** [comment]
This should work as you write. I need to take a look when I have access to a windows machine. Thank you for your report, I will look into this as soon as possible.

**Comment by pgundlach** [comment]
This works on my 64 bit Windows  7 VM:

```
C:\Users\Patrick Gundlach\Desktop\blubb>sp --layout "z:\a dir\layout.xml" --data
="z:\a dir\data.xml" 
```

Can you run the software with `--option xmlparser=lua` and --verbose and post the `publisher.protocol` file? 

like this:

```
C:\Users\Patrick Gundlach\Desktop\blubb>sp --layout "z:\a dir\layout.xml" --data
="z:\a dir\data.xml" --option xmlparser=lua --verbose
```

Here z: is just an alias to another folder on the file system.

**Comment by dnyamy** [comment]
Hello,
I ran the command with specified options and it worked fine. 
But what is suprising is that I ran again without the options and it still worked. 
Here is the publisher.protocol file. I had to zip it to have a Github compliant extension.
Thank you very much for your help
Regards
Dn
[publisher.protocol.zip](https://github.com/speedata/publisher/files/7197548/publisher.protocol.zip)

**Comment by pgundlach** [comment]
Glad it works! Thank you for the answer.
