### ISSUE TITLE
Ul attribute to customize symbol for bullet in unordered lists

### ISSUE THREAD

**Issue by OliverAut** [speedata/publisher#349]
New attribute for Ul to replace the default symbol for bullet points e.g. with a hyphen.

https://doc.speedata.de/publisher/de/grundlagen/textformatierung/index.html#ch-aufzaehlungslisten
https://tex.stackexchange.com/questions/62496/itemize-with-a-dash-instead-of-a-bullet/62497

**Comment by pgundlach** [comment]
Thank you very much for your report. I'll put this on my to do list.

You can use something like this in HTML mode:

`mystyle.css`:

```css
ul {
  list-style: none;
  padding-left: 1em;
 }

 ul li::before {
  content: "-";
  display: inline-block;
  width: 1em;
  margin-left: -1em;
 }
```

`layout.xml`:

```xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
    xmlns:sd="urn:speedata:2009/publisher/functions/en">

    <Stylesheet filename="mystyle.css"/>

    <Record element="data">
        <PlaceObject>
            <Textblock>
                <Paragraph>
                    <Value select="."></Value>
                </Paragraph>
            </Textblock>
        </PlaceObject>
    </Record>
</Layout>
```

and the data file (`data.xml`):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<data>
   <ul>
      <li>Hello</li>
      <li>nice</li>
      <li>world</li>
   </ul>
</data>
```

which gives you:
<img width="201" alt="hnw" src="https://user-images.githubusercontent.com/209434/148947514-03c797fc-0210-4b0e-9a68-6e7305822a18.png">

I know that the use case is limited, but perhaps its already suitable for your document.

**Comment by OliverAut** [comment]
Thank you for your fast response and perfect support.
The proposed solution works for me. The feature request is nice to have. But maybe this request could be combined with #311 for enumerations.

**Comment by pgundlach** [comment]
Lists will be handled some day. Currently there is no need besides HTML support. Thank you for the bug report.
