### ISSUE TITLE
sdluatex quit unexpectedly on macOS Catalina

### ISSUE THREAD

**Issue by brandonkal** [speedata/publisher#351]
Running the hello world example, `sp` returns this:
```
Run speedata publisher
Total run time: 47.510841ms
signal: segmentation fault
```
And macOS shows a dialog stating that "sdluatex quit unexpectedly"

**Comment by pgundlach** [comment]
Can you tell me which version (speedata Publisher) and which operating system version you have tried?

**Comment by brandonkal** [comment]
This is macOS 10.15.7 and I have tried versions 4.6.0 stable and 4.7.3

**Comment by pgundlach** [comment]
I see a problem when I run 4.7.3 on an even older Mac:

```
Run speedata publisher
/tmp/patrick/speedata-publisher/sw/lua/splib.lua:66: dlopen(libsplib.dylib, 5): no suitable image found.  Did find:
	/tmp/patrick/speedata-publisher/share/lib/libsplib.dylib: cannot load 'libsplib.dylib' (load command 0x80000034 is unknown)
	/tmp/patrick/speedata-publisher/share/lib/libsplib.dylib: stat() failed with errno=22
	/tmp/patrick/speedata-publisher/share/lib/libsplib.dylib: cannot load 'libsplib.dylib' (load command 0x80000034 is unknown)
	/tmp/patrick/speedata-publisher/share/lib/libsplib.dylib: stat() failed with errno=22
	/tmp/patrick/speedata-publisher/share/lib/libsplib.dylib: cannot load 'libsplib.dylib' (load command 0x80000034 is unknown)
	/tmp/patrick/speedata-publisher/share/lib/libsplib.dylib: stat() failed with errno=22
Total run time: 75.475605ms
```

I'll try to fix this before I come back to you. 
Thank you very much for the bug report!

**Comment by pgundlach** [comment]
I have no simple solution to that problem :-(

I keep this in mind and I will experiment to get this fixed, but I cannot promise anything. Sorry

**Comment by pgundlach** [comment]
The latest 4.7.4 works on Mojave, so it might work on Catalina. 

Not sure if you already gave up, but in case you didn't: could you give it a try? (there are now two binaries, amd64 and arm64 - take the amd64)
