### ISSUE TITLE
`--autoopen` works fine on Windows

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#371]
@pgundlach,

from `sp --help` on Win64, I get:

```
 --autoopen               Open the PDF file (MacOS X and Linux only)
```

No matter whether _SumatraPDF_ or _Acrobat Reader_, `--autoopen` works on my _Windows_ machine.

_Acrobat_ blocks the document once it has opened it.

But this really prevents PDF document generation.

Or am I missing something here?

Many thanks for the _Publisher_.

**Comment by pgundlach** [comment]
Probably a documentation error. I use `cmd /C start publisher.pdf`  to start the default viewer on windows. Thank you for your feedback, I'll add this to the documentation.

**Comment by pr-apes** [comment]
I have just provided a PR.

**Comment by pgundlach** [comment]
Thank you very much for the pull requests! Very much appreciated.
