### ISSUE TITLE
wrong link border with `<URL>`?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#381]
@pgundlach,

I have the following layout:

``` xml
<Layout
	xmlns="urn:speedata.de:2009/publisher/en"
	xmlns:sd="urn:speedata:2009/publisher/functions/en">
<PDFOptions showhyperlinks ="yes" />

<Record element="data">
<Output>
<Text>
    <Paragraph>
      <Value>Address:</Value>
	  <A href="https://speedata.de/publisher/"><URL><Value>https://doc.speedata.de/publisher/</Value></URL></A>
    </Paragraph>
</Text>
</Output>
</Record>
</Layout>
```

Because of `<URL>`, I get the following border (for each character):

![wrong-url](https://user-images.githubusercontent.com/51094960/176889090-b92ee443-9c4f-4f72-90b3-45c599c28877.png)

What am I missing here?

Many thanks for your help.

**Comment by pgundlach** [comment]
This doesn't look good. I hardly ever use a) the URL command and b) the showhyperlinks=yes, so I've missed this. Thank you for the report, I'll take a look.

**Comment by pgundlach** [comment]
Fixed in 4.9.8. Thank you very much for the report. Strictly speaking you don't need the URL element.

**Comment by pr-apes** [comment]
Many thanks for your fix, @pgundlach.

I know that `<URL>` is not required for the link, but I think it is mandatory for the text line break.

Or am I missing something here?

Many thanks for your help again.

**Comment by pgundlach** [comment]
@pr-apes that is correct (URL needed for line break)
