### ISSUE TITLE
option for a clean run?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#382]
@pgundlach,

I wonder whether there could be an option for a clean run (something like `sp [run] --clean`).

I know that `sp && sp clean` could achieve the same, but as long as no `--outputdir` is invoked.

With `sp --outputdir %USERPROFILE%\Desktop`, both `publisher.pdf` and `publisher.protocol` end in that directory.

From what I experience, I see no difference in running `sp clean` or `sp clean --outputdir %USERPROFILE%\Desktop` (both files are kept in the output directory).

Is that possible or have I overlooked something in the docs?

Many thanks for your help.

**Comment by pgundlach** [comment]
Sounds like a bug. I'll take a look, thank you. 

That said, I don't think there is a workaround at the moment.

**Comment by pgundlach** [comment]
There is a workaround:

    sp --wd %USERPROFILE%\Desktop clean

should work. This removes everything but the `.pdf` file.

**Comment by pr-apes** [comment]
Many thanks for the workaround, @pgundlach.

**Comment by pgundlach** [comment]
I'll close this as there is a workaround

**Comment by pr-apes** [comment]
Fine, but if not fixed, it should be documented.
