### ISSUE TITLE
directory separator in Windows

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#390]
@pgundlach,

I have the following sample:

``` xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en">

  <Record element="data">
    <SetVariable variable="myfile" select="$external_pdfdoc"/>
    <Loop select="sd:number-of-pages($myfile)" variable="page">
      <PlaceObject column="0mm" row="0mm">
        <Image file="{$myfile}" width="210mm" page="{$page}"/>
      </PlaceObject>
      <ClearPage/>
    </Loop>
  </Record>

</Layout>
```

With the common invocation `sp --autoopen`, I have the following possibilities (using _Windows_):

1. `-v external_pdfdoc=../doc-100.pdf`: included pages.
1. `-v external_pdfdoc=..\doc-100.pdf` pages not included.
1. `-v external_pdfdoc=%USERPROFILE%/Desktop/doc-100.pdf` pages not included.
1. `-v external_pdfdoc=%USERPROFILE%\Desktop\doc-100.pdf` pages not included.
1. `-v external_pdfdoc=c:/Users/username/Desktop/doc-100.pdf` included pages.
1. `-v external_pdfdoc=c:\Users\username\Desktop\doc-100.pdf` pages not included.

From https://doc.speedata.de/publisher/en/filenames/, I thought that options 4 and 6 would include the pages.

Am I missing something or is this the way _Publisher_ behaves?

Many thanks for your help.

**Comment by pgundlach** [comment]
How do you start the sp.exe program? On a command line? I assume that the backslashes must be doubled (but this should be documented)

**Comment by pr-apes** [comment]
Ok, I get it now.

**Comment by pr-apes** [comment]
So, as a general rule, when backslashes are used to specify _Windows_ paths, they have to be escaped as `\\`, don’t they?

**Comment by pgundlach** [comment]
It depends on where you use them. Within the layout or data files, one backslash should be fine. If provided at startup time from the command line, it should be doubled (so I assume).

**Comment by pr-apes** [comment]
Well, this is trial and error.

If I happened to have a more precise description when to escape backslashes, I would reopen the issue myself.

Many thanks for your help.
