### ISSUE TITLE
more verbose `<title>` info in docs

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#393]
@pgundlach,

would it be possible that the element `<html>/<head>/<title>` contained the contents of `<h1>` (besides _speedata Publisher manual_)?

I mean, taking https://doc.speedata.de/publisher/en/commandreference/image/ as an example, I think it is more informative to have:

``` xml
<title>Image · speedata Publisher manual</title>
````

than only 

``` xml
<title>speedata Publisher manual</title>
````

I realized that after not being sure about whether I was browsing image or options (and `<title>` was not very useful to find out).

I think it is worth to be implemented.

**Comment by pr-apes** [comment]
Many thanks for your help.

**Comment by pgundlach** [comment]
Thank you very much for the idea, this is much better than before. The documentation will be updated with the next release (soon).

**Comment by pr-apes** [comment]
Well, it was pretty obvious as I saw myself helpless...

**Comment by pr-apes** [comment]
Many thanks for the improvement.
