### ISSUE TITLE
horizontal and vertical clipping

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#394]
@pgundlach,

with the following [sample image (the cow from the ConTeXt distribution)](https://github.com/speedata/publisher/files/9070013/cow.pdf), I invoke `sp --dummy --autoopen -v external_pdfdoc=cow.pdf` with the following `layout.xml` contents:

``` xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en">

<Trace gridallocation="yes"/>

    <SetVariable variable="myfile" select="$external_pdfdoc"/>
  <Record element="data">
	<PlaceObject>
    <Image width="2cm" file="{$myfile}" clip="yes"/>
  </PlaceObject>
	<PlaceObject>
    <Image height="1cm" file="{$myfile}" clip="yes"/>
  </PlaceObject>
	<PlaceObject>
    <Image width="2cm" height="1cm" file="{$myfile}" clip="yes"/>
  </PlaceObject>
	<PlaceObject>
    <Image file="{$myfile}"/>
  </PlaceObject>
  </Record>
</Layout>
```

I can get horizontal or vertical clipping, but both seems to be impossible (with version 4.11.1).

Am I doing something wrong or missing something?

Many thanks for your help.

**Comment by pgundlach** [comment]
There is only one (either horizontal or vertical) clipping. clip="no" means (when width and height are given) distortion, with clip="yes" there is no distortion, but the image is scaled so that the whole area (width and height) is filled with portions of the image.

**Comment by pr-apes** [comment]
Just to confirm (I barely understand this), would both clippings achievable with transformations such as the ones you describe in https://github.com/speedata/publisher/discussions/395#discussioncomment-3106364?

**Comment by pgundlach** [comment]
> Just to confirm (I barely understand this), would both clippings achievable with transformations such as the ones you describe in [#395 (comment)](https://github.com/speedata/publisher/discussions/395#discussioncomment-3106364)?

Yes, but this is probably tedious calculation (works with DTP points and scale calculations).

**Comment by pr-apes** [comment]
I wonder whether it would be possible to implement custom clipping with `clipping="both"` and `origin-x` and `origin-y` (with units as in `width` and `height`)

I originally intended to translate a rather simple ConTeXt command:

``` tex
\clip[hoffset=62.5mm, voffset=0.5mm, width=87.5mm, height=54mm]
```

But I ignore how hard would be to implement such feature in _Publisher_.

**Comment by pr-apes** [comment]
I close the issue for now (not a requirement until just before production).

**Comment by pgundlach** [comment]
I'll re-open it because I am thinking of adding a few attributes to the transform command to make it easier to use (I know that the transformation matrix is hard to use).

**Comment by pgundlach** [comment]
I think I'll add a new command `Clip` to be used something like this:

```
<Clip left="3mm" right="2mm" top="5mm" bottom="3mm">
    <Image width="5cm" file="_sampleb.pdf" />
</Clip>
```

to clip any kind of contents. Do you think this interface (left/right/top/bottom) is suitable or do you prefer something like the ConTeXt hoffset/voffset/width/height)?

**Comment by pr-apes** [comment]
@pgundlach,

many thanks for this element.

The ConTeXt values are more familiar to me. But this should not be a reason to decide.

Your approach is clearer (once I got what it meant 😅), but also requires to do the math,

I wonder whether having `left`, `right`, `top`, `bottom` and also `width` and `height` is an option.

I think it really makes sense, but I may be missing something.

Many thanks for your excellent work.

**Comment by pr-apes** [comment]
Many thanks for the new implementation, @pgundlach.

**Comment by pgundlach** [comment]
It is part of version 4.11.3 (available for download now)

**Comment by pr-apes** [comment]
I had already downloaded it (although I am testing other things).

I really appreciate this huge step in ease of use for image clipping.

Many thanks again.
