### ISSUE TITLE
charset in CSV file

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#398]
@pgundlach,

I have just added `αβγ` to a cell in `https://github.com/speedata/examples/blob/master/technical/csvreader/us-500.csv` (saving hte contents as UTF-8 text file).

I generated the PDF document again and there was no error.

So I guess the default charset for CSV files may be UTF-8.

Many thanks for your help.

**Comment by pgundlach** [comment]
Most likely so. I think I should document this. Thank you!
