### ISSUE TITLE
conditional expression in XPath

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#401]
@pgundlach,

https://doc.speedata.de/publisher/en/xpathfunctions/#_the_following_xpath_expressions_are_handled_by_the_software contains as last item:

*  Simple if/then/else expressions: `if (…​) then …​ else …​`

Sorry, I’m not being picky, but `if (…) then … else if (…) then … else …` is also allowed.

Maybe I’m being oversensitive here, but with simple (conditional) expressions, I thought there was no `else if` here (compare it to `\if … \else …\fi` in TeX).

Just a comment that may turn into better wording in the documentation.

Many thanks for your excellent work.

**Comment by pgundlach** [comment]
I am not sure I understand your comment. I want to express that what is written on 
https://www.wwp.northeastern.edu/outreach/seminars/_current/presentations/xslt/mdh_xsl_conditionals_tutorial_04.xhtml
is allowed in the select/test attributes of the speedata Publisher. Is my wording incorrect?

**Comment by pr-apes** [comment]
I have just realized that my approach is wrong.

`else if` (with no ending word) may be understood as a nested conditional (what could not be the case if a closing operator were used [such as in _Lua_ or TeX, to name two]).

Sorry for the wrong report.
