### ISSUE TITLE
values for `<Clip method="">`

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#405]
@pgundlach,

I’m not a native speaker, but I would say that clipping involves cutting (https://www.m-w.com/dictionary/clip, https://dictionary.cambridge.org/dictionary/english/clip).

I would propose to replace `shrink` with `clip` and `clip` with `frame` (especially now, that the element and this attribute are brand–new).

It also makes sense that the default method of  `<Clip>` is clipping.

Just in case it might help also to understand what the method does.

Many thanks for your help.

**Comment by pgundlach** [comment]
Good point. Next version will have those changed. Thank you again.

**Comment by pr-apes** [comment]
Many thanks for the implementation.
