### ISSUE TITLE
attribute index?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#406]
@pgundlach,

I wonder whether it would be possible to have in the documentation an attribute index.

I mean, some kind of list that relates attributes with the elements where they are deployed.

Of course, this proposal would only make sense if the list might be (almost) automatically generated.

Many thanks for your help.

**Comment by pgundlach** [comment]
So a list for example 

 `clip`
   - Clip
   
 `leader` 
   - HSpace

 `width`
   - Textblock
   - Image
   - Barcode
   - HSpace
   - Table
  
where all commands that have a width attribute are listed and linked to the command itself?

**Comment by pr-apes** [comment]
Yes, this was my idea.

**Comment by pgundlach** [comment]
Next version (now online) has the attribute index, but I am not sure if this is a good idea. I'd love to hear your opinion.

https://doc.speedata.de/publisher/en/commandreference/ref_attribute_index/

**Comment by pr-apes** [comment]
This really useful to search for attributes present in different elements (it helps to understand how elements are structured in _Publisher_).

Even if many users may find no use in this list, I guess this will not hurt them.

Many thanks for your help.
