### ISSUE TITLE
variables with backslashes

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#411]
@pgundlach,

having this layout:

``` xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en">

  <Record element="data">
    <PlaceObject>
      <Textblock>
        <Paragraph>
          <Value select="if (sd:variable-exists('cfn')) then 'yes' else 'no'"/>
        </Paragraph>
      </Textblock>
    </PlaceObject>
  </Record>

</Layout>
```

The following invocation `sp --dummy -v cfn="\a\b\c"` outputs `no`, but `sp --dummy -v cfn="\a\b"` outputs `yes`.

This may be the underlying cause of #409. I’m afraid that backslashes are essential for complete paths in Windows (this is what I’m trying to pass as variable [through a batch file]).

Many thanks for your help.

**Comment by pgundlach** [comment]
Can you create a simple filter such as the following to show the variables?

```lua
runtime = require("runtime")


for key, value in pairs(runtime.variables) do
    print(key,string.format("%q",value))
end


os.exit(0)
```

**Comment by pr-apes** [comment]
My results are the following:

```
>sp --filter a.lua -v cfn="\a\b"
cfn     "\\a\\b"

>sp --filter a.lua -v cfn="\a\b\c"
cfn     "\\a\\b\\c"
```

The first value for `cfn` variable would output `yes` and the second value would output `no`.

I wonder whether you need other data for this.

Many thanks for your help.

**Comment by pgundlach** [comment]
OK, thanks, this will be fixed in the next version.

**Comment by pr-apes** [comment]
Many thanks for your help.
