### ISSUE TITLE
issue with download links

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#438]
@pgundlach,

since the release of Publisher Pro, both https://download.speedata.de/dl/speedata-publisher-windows-amd64-latest.zip and https://download.speedata.de/dl/speedata-publisher-linux-amd64-latest.zip seem to point to unreachable Pro binaries.

Would it be possible that those links could continue working as they were working and could you create new links for the Pro version at https://download.speedata.de/dl/speedata-publisherpro-windows-amd64-latest.zip and https://download.speedata.de/dl/speedata-publisherpro-linux-amd64-latest.zip?

Many thanks for your help.

**Comment by pgundlach** [comment]
This is an error. I will fix that. Thank you for raising this issue.

**Comment by pgundlach** [comment]
Should be fixed now. Thanks again!

**Comment by pr-apes** [comment]
Many thanks for the fix.
