### ISSUE TITLE
size in attachments

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#439]
@pgundlach,

this line

https://github.com/speedata/publisher/blob/750feb974ddb169f469d814fdf4975a7e99b7ac4/src/lua/publisher.lua#L7172

is responsible for code such as:

``` pdf
<<
  /Params <<
    /ModDate (D:20220824132726+00'00')
  >>
  /Subtype /text#2Fxml
  /Type /EmbeddedFile
  /Length 5398
>>
```

But without `/Size` in `/Params`, Acrobat won't display file size.

![nosize-fs8](https://user-images.githubusercontent.com/51094960/191712193-7ebf1ba1-0d2a-4999-9b95-0d04dbc2d076.png)

So the final code should read:

``` pdf
<<
  /Params <<
    /ModDate (D:20220824132726+00'00')
    /Size 5398
  >>
  /Subtype /text#2Fxml
  /Type /EmbeddedFile
  /Length 5398
>>
```

This would make a similar image (taken from another PDF document):

![size-fs8](https://user-images.githubusercontent.com/51094960/191712181-44b627c5-7b19-48fa-8369-2dcaeef12e21.png)

I'm afraid I cannot provide a patch, since I don't know how `/Length` is included from the Lua code.

Many thanks for your help.

**Comment by pgundlach** [comment]
Will be in the next version

**Comment by pr-apes** [comment]
Many thanks for the implementation.
