### ISSUE TITLE
XPath function `matches(<input>, <regexp>)`?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#453]
@pgundlach,

I wonder whether it would be possible to include in Publisher the XPath function `matches()` (which seems to be `contains()` with regexp functionality).

Many thanks for your help.

**Comment by pr-apes** [comment]
I see that mimicking the function wouldn't be that hard, but I never touched Go or C.

Even then, I don't know how to compile this, so I wouldn't be able to test my proposed changes.

**Comment by pgundlach** [comment]
This would be useful and could be done without too much hassle. But I cannot give you an ETA for this.

**Comment by pr-apes** [comment]
I'm not in a hurry.

**Comment by pgundlach** [comment]
Will be in next version

**Comment by pr-apes** [comment]
Great news!

**Comment by pr-apes** [comment]
Many thanks for the new release, @pgundlach.
