### ISSUE TITLE
macOS: module 'splib' not found

### ISSUE THREAD

**Issue by LdBeth** [speedata/publisher#454]
On macOS Intel, sp Version: 4.13.4
```
$ sp list-fonts
/usr/local/etc/speedata/sw/lua/sdscripts.lua:9: module 'splib' not found:
	no field package.preload['splib']
	no file '/usr/local/etc/speedata/sw/lua/splib.lua'
	no file '/usr/local/etc/speedata/lib/splib.lua'
	no file '/usr/local/etc/speedata/sw/lua/common/splib.lua'
	no file '/usr/local/etc/speedata/share/lib/splib.so'
	no file '/usr/local/etc/speedata/share/lib/splib.dll'
Total run time: 10.416556ms
exit status 1
Total run time: 10.465959ms
```

There is `/usr/local/etc/speedata/share/lib/libsplib.dylib` that seems has the symbols matches the functions , but it seems not compiled to be loaded by lua as it lacks `luaopen_` symbol.

**Comment by pgundlach** [comment]
I can reproduce the problem. Thank you very much for the report, I try to fix this as soon as possible.

**Comment by pgundlach** [comment]
I forgot to include the correct libraries here while switching from LuaJIT to my own C-library. Thanks again for your report! The version 4.13.5 should work as expected.
