### ISSUE TITLE
Regression: NoBreak can only have one Value child

### ISSUE THREAD

**Issue by iclukas** [speedata/publisher#455]
Somewhere between v4.0.1 and v4.2.0 there was a regression with the ``<NoBreak>`` element. It used to work with multiple ``<Value>`` children, but now sp will just crash. Might be related to #410 

This example works with 4.0.1 but crashes 4.2.0 and later:

```xml
<Layout
	xmlns="urn:speedata.de:2009/publisher/en"
	xmlns:sd="urn:speedata:2009/publisher/functions/en">

	<Record element="data">
		<PlaceObject>
			<Textblock width="5" height="2">
				<Paragraph>
					<NoBreak reduce="fontsize">
						<Value>lorem</Value><Value> ipsum</Value>
					</NoBreak>
				</Paragraph>
			</Textblock>
		</PlaceObject>
	</Record>
</Layout>
```

**Comment by pgundlach** [comment]
Thank you very much for the bug report. 

(this is not easy to fix....)
