### ISSUE TITLE
page numbers in XPath functions with PDF images

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#456]
@pgundlach,

I have just realized that I cannot find a way to specifiy page numbers for `sd:aspectratio()`, `sd:imagewidth()` and `sd:imageheight()`.

Nothing prevents that different pages may have different dimensions in the same PDF document.

If this might help, having a syntax such as `(image:page_number)` may avoid confusions with units in `sd:imagewidth()` and `sd:imageheight()`.

Many thanks for your help.

**Comment by pgundlach** [comment]
Good point, I have not thought of this. The colon syntax seems legit. Thank you very much for this suggestion.

**Comment by pgundlach** [comment]
Now in version 4.13.6. Thanks again for the feature request.

**Comment by pr-apes** [comment]
Many thanks for the new release.
