### ISSUE TITLE
`<Pagetype>` misplacing content?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#464]
@pgundlach,

this almost obvious sample (run with `sp --dummy --jobname=misplaced`):

``` xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
    xmlns:sd="urn:speedata:2009/publisher/functions/en">

  <Record element="data">
      <Output>
        <Text>
          <Paragraph>
            <Value select="sd:dummytext()"/>
          </Paragraph>
        </Text>
      </Output>
  </Record>
</Layout>
```

With this source run with `sp --dummy -v pdfdoc=misplaced.pdf`:

``` xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en">

  <!--<Pageformat-->
    <!--width="{if (not(sd:mode('no-booklet'))) then '297mm' else '210mm'}"-->
    <!--height="{if (not(sd:mode('no-booklet'))) then '210mm' else '297mm'}"/>-->

  <Pagetype test="not(sd:mode('no-booklet'))" width="297mm" height="210mm"/>

  <Record element="data">
      <PlaceObject column="{$_pagewidth * 0.75}" row="{$_pageheight div 2}" hreference="center" vreference="middle">
        <Image file="{$pdfdoc}" width="{$_pagewidth div 2}" page="1"/>
      </PlaceObject>
  </Record>

</Layout>
```

The page is misplaced with `<Pagetype>`:

![misplaced-a-fs8](https://user-images.githubusercontent.com/51094960/220888600-d87b7ca9-5584-41ec-a950-70fde0f807d3.png)

A workaround is the commented `<Pageformat>`:

![misplaced-000001-fs8](https://user-images.githubusercontent.com/51094960/220888557-b6b8226f-d14a-4d69-99c3-507a12f06896.png)

I don't know what am I or is missing here.

Many thanks for your help.

**Comment by pgundlach** [comment]
This is a bug and I don't really know how to work around it. This is a more simple test case:


```
<Layout xmlns="urn:speedata.de:2009/publisher/en"
	xmlns:sd="urn:speedata:2009/publisher/functions/en">

	<Pagetype name="foo" test="true()" width="297mm" height="210mm" />

	<Record element="data">
		<!-- <Message select="sd:current-row()"/> -->
		<Message select="$_pagewidth"/>
		<Message select="$_pageheight"/>
	</Record>

</Layout>
```

Workaround:

If you uncomment the first Message, the page is initialised by the `sd:current-row()` and then the page width and height are set correctly.

This should be documented though....

**Comment by pgundlach** [comment]
Perhaps I should stop using these page-dependent variables and expose them as functions?

**Comment by pgundlach** [comment]
There are now two xpath functions for page detection (`sd:pagewidth()` and `sd:pageheight()`) See https://doc.speedata.de/publisher/en/xpathfunctions/index.html#_sd_layout_functions

**Comment by pr-apes** [comment]
These functions are great to have.

Many thanks for your help.

**Comment by pr-apes** [comment]
I have just tested them and I'm afraid that these functions have problems to place content:

``` xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en">

  <Record element="data">
    <!--<PlaceObject column="{$_pagewidth * 0.5}" row="{$_pageheight div 2}" hreference="center" vreference="middle">-->
    <!--  <Image file="{$pdfdoc}" width="{$_pagewidth div 2}" page="1"/>-->
    <!--</PlaceObject>-->
    <PlaceObject column="{sd:pagewidth('sp') * 0.5}" row="{sd:pageheight('sp') div 2}" hreference="center" vreference="middle">
      <Image file="{$pdfdoc}" width="{sd:pagewidth('sp') div 2}" page="1"/>
    </PlaceObject>
  </Record>

</Layout>
```

With the code above (run invoking `sp --dummy -v pdfdoc=misplaced.pdf` and with the sample from [the original comment](https://github.com/speedata/publisher/issues/464#issue-1596665484)), there is no visible placement at all (Publisher reports conflict in grid).

**Comment by pgundlach** [comment]
You need to add the unit `sp`, otherwise this is without dimension and will be interpreted as grid cells.

```xml
    <PlaceObject column="{sd:pagewidth('sp') * 0.5}sp" row="{sd:pageheight('sp') div 2}sp" hreference="center" vreference="middle" frame="solid">
      <Image file="{$pdfdoc}" width="{sd:pagewidth('sp') div 2}sp" page="1"/>
    </PlaceObject>
```

**Comment by pr-apes** [comment]
@pgundlach,

I wonder whether it would be possible that `sd:pagewidth()` could add the dimension in the result and behave similar to `$_pagewidth`.

This would result in the same behavior from `$_pagewidth` and `sd:pagewidth()`. Since the function is brand-new, it won't break backwards-compatibility.

Many thanks for your help.

**Comment by pgundlach** [comment]
But it makes calculation easier if I leave out the unit and it is closer to the behaviour of the other width/height functions.

**Comment by pr-apes** [comment]
In that case, it is perfectly fine for me.

Many thanks for your help.
