### ISSUE TITLE
issue with `/CropBox` overflowing `/MediaBox`

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#468]
@pgundlach,

here is the following ConTeXt source for an uncompressed PDF document:

``` tex
\nopdfcompression
\setupinteractionscreen
  [width=fit]
\setuplayout
  [standard]
  [backspace=.7\textwidth,
   cutspace=\cutspace,
   width=middle]
\starttext
\startmakeup[page]
\null
\stopmakeup
\startmakeup[standard]
\null
\stopmakeup
\stoptext
```

`/CropBox` from page 1 fits inside its `/MediaBox`. But on page 2, `/CropBox` overflows its `/MediaBox`.

`/MediaBox` is object 3 on both pages:

```
3 0 obj
[ 0 0 595.275590072 841.88975789 ]
endobj
```

`/CropBox` is object 5 on page 1 and object 8 on page 2:

```
5 0 obj
[ 0 0 595.27559 841.889758 ]
endobj
```

```
8 0 obj
[ 0 0 968.199847 841.889758 ]
endobj
```

Processing the output with the following layout:

``` xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en">

  <Record element="data">
    <Loop select="sd:number-of-pages($pdfdoc)" variable="pg">
      <PlaceObject row="{$_pageheight * 0.5}" column="{$_pagewidth * 0.5}"
       hreference="center" vreference="middle" frame="solid">
        <Image visiblebox="mediabox" file="{$pdfdoc}"
         width="{sd:pagewidth('sp') * 0.5}sp" page="{$pg}"
         rotate="{if (not(sd:aspectratio(concat($pdfdoc, ':', $pg)) > 1)) then '0' else '90'}"/>
      </PlaceObject>
      <ClearPage/>
    </Loop>
  </Record>
</Layout>
```

I get page 2 rotated, although `<Image visiblebox="mediabox">` is specified.

Editing values for `/CropBox` to have a higher width value, page 1 gets rotated too.

So, I'm afraid that Publisher ignores `visiblebox="mediabox"`, choosing the largest box (when one is available).

I think Publisher should honor the specified `visiblebox`.

Even from the PDF–1.7 specification (https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf#page=636):

> The crop, bleed, trim, and art boxes shall not ordinarily extend beyond the boundaries of the media box. If they do, they are effectively reduced to their intersection with the media box.

https://github.com/speedata/publisher/blob/f9ef96dc1b90552e210188e273c72706972e15a2/src/lua/publisher.lua#L6850 seems to select `"crop"` when larger than any given `visiblebox` (but I don't know how to fix this).

Could you fix this issue?

Many thanks for your help.

**Comment by pgundlach** [comment]
Would it be possible to provide the sample PDF?

**Comment by pr-apes** [comment]
Here you have it: [crop-media-sample.pdf](https://github.com/speedata/publisher/files/10861304/crop-media-sample.pdf).

**Comment by pgundlach** [comment]
I am not sure if I understand this correctly. Both pages have the same media box, but different crop box (1: portrait, 2: landscape - where the width is larger than the width of the media box). 

The function `sd:aspectratio(..)` currently uses the crop box to determine the aspect ratio but fails, because it should  use the minimum width of (cropbox,mediabox) and the minimum height of (cropbox, media box), correct?

**Comment by pr-apes** [comment]
> I am not sure if I understand this correctly. Both pages have the same media box, but different crop box (1: portrait, 2: landscape - where the width is larger than the width of the media box).

Both pages have the same mediabox and different values for cropbox.

I think these are rather uncommon values for boxes in pages, but the PDF spec doesn't forbid them.

> The function `sd:aspectratio(..)` currently uses the crop box to determine the aspect ratio but fails, because it should use the minimum width of (cropbox,mediabox) and the minimum height of (cropbox, media box), correct?

Right. But let me explain another related issue.

It is really hard to have variables and XPath functions that use the cropbox, when other box (mediabox in this case) has been specified for `<Image visiblebox="">`.

If other `visiblebox` is specified, I think that all variables and XPath functions should use the specified box.

Otherwise, this may lead to miscalculations, such as it has happened in this case.

**Comment by pgundlach** [comment]
> > The function `sd:aspectratio(..)` currently uses the crop box to determine the aspect ratio but fails, because it should use the minimum width of (cropbox,mediabox) and the minimum height of (cropbox, media box), correct?
> 
> Right. But let me explain another related issue.

this is not implemented (yet). I still think if this will break existing documents if I change it.
 
> It is really hard to have variables and XPath functions that use the cropbox, when other box (mediabox in this case) has been specified for `<Image visiblebox="">`.
> 
> If other `visiblebox` is specified, I think that all variables and XPath functions should use the specified box.
> 
> Otherwise, this may lead to miscalculations, such as it has happened in this case.

this is not possible since these two don't interact (and I don't want them to interact - backwards compatibility concerns).

I have created a colon syntax explained at https://doc.speedata.de/publisher/en/images/#ch-colonsyntax (needs a bit of updating).

**Comment by pr-apes** [comment]
Many thanks for having fixed this, @pgundlach.
