### ISSUE TITLE
PDF (offline) documentation?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#469]
@pgundlach,

since offline documentation is removed from the installation, I think it would make sense to include a PDF document with it.

This would also be the first and most complete sample of PDF generation with Publisher.

This could also be opened when `sp doc` would be invoked.

Many thanks for your help.

**Comment by pgundlach** [comment]
I don't think this is very realistic. This would be a pretty big undertaking and I believe that for text only documents there are better options than the speedata Publisher (TeX for example). I keep this in mind but close the issue...

**Comment by pr-apes** [comment]
In that case, it would be useful to include the ePub document.
