### ISSUE TITLE
`decode_xml()` created table name?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#480]
@pgundlach,

I read in the documentation [about `decode_xml()`](https://doc.speedata.de/publisher/en/advancedtopics/preprocessing/#_xml):

> Reads an XML file and creates a table in the format from `encode_table`.
> Return value `1` is a bool (success), value `2` is the error message if the first value is `false` or the table if the first value is `true`.

Is there any way to influence the table name? At least, which is the name of the imported table?

I'm afraid imported XML data are of no use in the filter, unless I can access them.

Sorry, but I guess either the documentation or myself lacks something.

Many thanks for your help.

**Comment by pgundlach** [comment]
Does this help?

```lua
local xml = require("xml")
dofile("debug.lua")

ok ,tab = xml.decode_xml("data.xml")
printtable("data",tab)
```

data.xml:
```xml
<root>
    <child>1</child>
    <child>2</child>
    <child><abc>abc</abc></child>
</root>
```

lua table:

```lua
data = {
  [1] = "\n    "
  [2] = {
    [1] = "1"
    ["_type"] = "element"
    ["_name"] = "child"
  },
  [3] = "\n    "
  [4] = {
    [1] = "2"
    ["_type"] = "element"
    ["_name"] = "child"
  },
  [5] = "\n    "
  [6] = {
    [1] = {
      [1] = "abc"
      ["_type"] = "element"
      ["_name"] = "abc"
    },
     ["_type"] = "element"
     ["_name"] = "child"
    },
    [7] = "\n"
    ["_type"] = "element"
    ["_name"] = "root"
 }
```

(formatting is a bit broken)

**Comment by pgundlach** [comment]
the table above is the second argument of `xml.decode_xml()`

**Comment by pr-apes** [comment]
Sorry for the delayed reply, @pgundlach.

I have to check this later, but I have a comment.

I cannot use `dofile("debug.lua")` unless full path is specified. I wonder whether this is intended.

Many thanks for your help.

**Comment by pgundlach** [comment]
This works for me where debug.lua is in the current directory. 

I will close this as fixed. If there are still problems, please re-open.

**Comment by pr-apes** [comment]
It works for me with current version (4.13.12) as `require("debug")`.

Is this the standard way of invoking it?

**Comment by pgundlach** [comment]
Actually I am not a Lua expert regarding `dofile()` and `require()`. I use `dofile("debug.lua")` for  my debugging script, but require could also work.

**Comment by pr-apes** [comment]
In my case, `require()` seems to find the file in the Publisher tree.

`dofile()` requires full path and extension to find the file.

**Comment by pr-apes** [comment]
From _ Programming in Lua _ (first edition), section _8.1 – The `require` Function_ (https://www.lua.org/pil/8.1.html):

> Lua offers a higher-level function to load and run libraries, called `require`. Roughly, require does the same job as `dofile`, but with two important differences. First, `require` searches for the file in a path; second, `require` controls whether a file has already been run to avoid duplicating the work. Because of these features, `require` is the preferred function in Lua for loading libraries.
