### ISSUE TITLE
Rowspan/Colspan bug

### ISSUE THREAD

**Issue by Demosteneus** [speedata/publisher#481]
Hello,

I think there is another issue with rowspan / colspan. 

This time something simpler:

The below example1.zip (layout.xml and data.xml) works and produces below output:
![image](https://user-images.githubusercontent.com/68335318/226860897-47cbf5ed-df81-4f29-9c58-4130e246a262.png)

But if I want to span also row3 cell1 to row3 cell2 (see example2.zip) this fails with error: 
`tabular.lua:1251: attempt to index a nil value (local 'current')`

[example1.zip](https://github.com/speedata/publisher/files/11038476/example1.zip)
[example2.zip](https://github.com/speedata/publisher/files/11038509/example2.zip)

**Comment by pgundlach** [comment]
Thank you very much for your report. I will take a look.
