### ISSUE TITLE
`print(package.config:sub(1,1))` nil error

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#485]
@pgundlach,

minimal filter:

``` lua
print(package.config:sub(1,1))

if true then
  os.exit(0)
end
```

Invoking it with `sp --filter=filter.lua`, I get:

```
C:\helloworld\filter.lua:1: attempt to index a non-table object(nil) with key 'sub'
stack traceback:
    C:\\helloworld\filter.lua:1: in main chunk
    [G]: ?
```

I don't know whether I'm missing something.

Many thanks for your help.

**Comment by pgundlach** [comment]
Works here on macOS. Maybe this is a windows issue. I'll have a look on next  Monday.

**Comment by pgundlach** [comment]
Confirmed that package.config is nil on windows

**Comment by pgundlach** [comment]
package.config will be part of the next version

**Comment by pr-apes** [comment]
Many thanks for the fix.

**Comment by pr-apes** [comment]
Sorry, I didn't want to close the issue.

**Comment by pgundlach** [comment]
Should work in the current version (4.13.12) which is online now.

**Comment by pgundlach** [comment]
I will close this as fixed. If there are still problems, please re-open.

**Comment by pr-apes** [comment]
It works fine now.

Many thanks for the new release.
