### ISSUE TITLE
wrong image margins?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#491]
@pgundlach,

I tried to add margins to an image (after ce14a72aaef7e4536daf10f0b1709a53e9f53acc) and I got this source:

``` xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
  xmlns:sd="urn:speedata:2009/publisher/functions/en">

  <Record element="data">
     <PlaceObject frame="solid" framecolor="green" rulewidth="1pt">
      <Image file="_samplea.pdf" width="5cm" margin-left="12.5mm"
	    margin-right="12.5mm" margin-top="12.5mm" margin-bottom="12.5mm"/>
     </PlaceObject>
  </Record>
</Layout>
```

But I get the following output:

![wrong-margins-fs8](https://user-images.githubusercontent.com/51094960/233948010-637d84ef-1734-4e20-a675-4a12df8977b4.png)

Left and right margins are placed as a wider left margin and top and bottom margins are placed as a higher top margin.

Is my code wrong or is this a bug in Publisher?

Many thanks for your help.

**Comment by pgundlach** [comment]
Looks like a bug. Thanks!
