### ISSUE TITLE
allow no namespace in layout?

### ISSUE THREAD

**Issue by pr-apes** [speedata/publisher#493]
@pgundlach,

in order to perform comparison with the same source files, it would be great that Publisher could read instructions from the layout file, even if the `<Layout>` element had no namespace specified.

This is what xts does and it would help to compare both outputs and compilation times.

Many thanks for your help.

**Comment by pgundlach** [comment]
What xts does is incorrect. The two layout languages will not be the same so it might not make much sense to do so. I'd rather keep a sanity check in both the publisher and xts.

**Comment by pr-apes** [comment]
Ok, just comparing them. I thought this might be an easier way.
