### ISSUE TITLE
🙏 Moving the grid foreground and background

### ISSUE THREAD

**Issue by pgundlach** [speedata/publisher#512]
Should be an option, but I don't know the best name. Perhaps another option `gridlocation="foreground"` or so.

### Discussed in https://github.com/speedata/publisher/discussions/511

<div type='discussions-op-text'>

<sup>Originally posted by **Cicorione** July 14, 2023</sup>
Hi Patrick,

during my previous tests I used a background image and I noticed the image background was covering the grid, I wonder if you can add an option to move the grid foreground like:

```xml
<Trace grid="yes" foreground="yes"/> # default would be "no"
```

Thanks... 🙏</div>

**Comment by Cicorione** [comment]
Hi Patrick,

I checked out with my son which his main language is English and `location` is approved, although I prefer shorter names and I would suggest `gridlayer="background/foreground"`  or `layer="foreground"` but definitely `gridlocation` is good to go! 👍

**Comment by pgundlach** [comment]
I have implemented `gridlocation` which can be `foreground` and `background` (default). New version will be uploaded in a minute.
