### ISSUE TITLE
Issue or pebcak?

### ISSUE THREAD

**Issue by Cicorione** [speedata/publisher#516]
Hi Patrick,

I am having some issue during the compilation and I wonder it if is me or a bug...

Here are my files (From Windows)

```
    Directory: X:\Marketing\New Catalogs


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/29/2023   9:50 AM                00 references
d-----         7/20/2023  10:42 AM                sec
-a----         8/29/2023   3:09 PM            132 data.xml
-a----         8/29/2023   4:00 PM           2007 layout.xml
-a----         8/29/2023   9:56 AM          18203 layout_000.xml
-a----         8/29/2023   2:32 PM           1527 layout_001.xml
-a----         8/29/2023   1:22 PM             84 publisher-aux.xml
-a----         8/29/2023   4:02 PM              9 publisher.finished
-a----         8/29/2023   4:02 PM              0 publisher.pdf
-a----         8/29/2023   4:02 PM           2314 publisher.protocol
-a----         8/29/2023   4:02 PM            560 publisher.status
-a----         8/29/2023   4:02 PM             13 publisher.vars
-a----         8/29/2023   3:53 PM           2149 sec01.xml
-a----         8/29/2023   2:10 PM            104 toc.xml
```

Even when I run `sp.exe --data=data.xml`, `Speedata` ignores the directive (or at least is what I presume) and goes looking into `/sec/01/` to find the first data.xml available (which is there but it is not a `Speedata` file)

```
 sp.exe --data=data.xml
Run speedata publisher 4.14.0 (Pro)
Loading file sdini.lua ... done
...
Load file: "publisher.lua" ... done
Start processing
Running LuaTeX version 1.13.2 on windows
Loading hyphenation patterns "hyph-en-gb.pat.txt".
...
Preload font "texgyreheros-bolditalic.otf" at 8pt (id: 8)
...
Loading aux file "X:\\Marketing\\New Catalogs\\publisher-aux.xml"
Loading data file "X:\\Marketing\\New Catalogs\\sec\\01\\data.xml"
...
Stop processing data
1 errors occurred
Duration: 0.033206 seconds
```

I am an expert in **pebcaks** but today wasn't working anything and who know it was because it has been reading all the time the wrong `data.xml` file? 🤔

**Comment by pgundlach** [comment]
This is a “feature” of the speedata Publisher 

https://doc.speedata.de/publisher/en/basics/fileorganization/#ch-fileorganization

When the speedata Publisher starts, it reads the current directory and its child directories and builds a local search dictionary. 

So data.xml is found in both the current directory and in \sec\01\data.xml so it does not know which one to chose.

Either 
 1. move the sec directory to another place
 2. rename data.xml in \sec\01
 3. or ...
 4. use `--no-local` to stop the recursive search

Does that help?

**Comment by Cicorione** [comment]
Thank you @pgundlach you're the best!
