### ISSUE TITLE
Overlay interdependence between children

### ISSUE THREAD

**Issue by serpent213** [speedata/publisher#520]
While you are on the hunt, could be I found another oddity.

Following structure for the page header (implemented [here](https://github.com/serpent213/afuchs/blob/beec88cf483b079be929f3014f30633406738eaf/layout.xml#L45)):

```xml
<PlaceObject>
  <Overlay>
    <Textblock ...>
    <!--
    <Position>
      <Textblock ...>
    </Position>
    -->
    <Position>
      <Textblock ...>
    </Position>
  </Overlay>
</PlaceObject>
```

Works as expected:

<img width="1094" alt="Screenshot 2023-09-20 at 12 45 15" src="https://github.com/speedata/publisher/assets/106662/5fa20d7a-e81b-4225-8e0c-f0d8810a3003">

But when removing the comment markers to enable the centered text, the last `Textblock` changes its position:

<img width="1094" alt="Screenshot 2023-09-20 at 12 44 16" src="https://github.com/speedata/publisher/assets/106662/1233e619-4dfb-40ab-ba09-709a13e0fee8">

Or is `Overlay` supposed to be applied differently?

**Comment by pgundlach** [comment]
Yes, this is a bug....

**Comment by pgundlach** [comment]
Just for the record: This kind of header can be created with a table:

```xml
<PlaceObject row="1" column="1">
    <Table fontfamily="text" stretch="max">
        <Tr>
            <Td align="left">
                <Paragraph>
                    <Value>Amateurfunk Cheat Sheet V</Value>
                </Paragraph>
            </Td>
            <Td align="center">
                <Paragraph>
                    <Value>0Z0BSP</Value>
                  </Paragraph>
            </Td>
            <Td align="right">
                <Paragraph>
                    <Value>2023 Steffen Beyer</Value>
                </Paragraph>
            </Td>
        </Tr>
        <!-- control spacing, color '-'' means no color -->
        <Tablerule rulewidth="4pt" color="-"/>
        <Tablerule rulewidth="0.6pt" />
    </Table>
</PlaceObject>
```

**Comment by serpent213** [comment]
Thank you, [using a table now](https://github.com/serpent213/afuchs/blob/07af66b93b925eaa0129d6ba5282f67d8657f2f2/layout.xml#L45) with added column specs:

```xml
<Columns>
  <Column align="left" width="8" />
  <Column align="center" width="16" />
  <Column align="right" width="8" />
</Columns>
```

Tried `width="max"` first for the center column, which didn't work as expected...

**Comment by pgundlach** [comment]
Instead of using "8","16","8" as values you can use "1*", "2*", "1*", you don't have to do the calculation yourself. But this works only if you use `stretch="max"` (not `width="max"`) on the Table.
