### ISSUE TITLE
Can't use switch case on page margins

### ISSUE THREAD

**Issue by Cicorione** [speedata/publisher#523]
Hi @pgundlach 

I was unsure where posting this, I am concern that is another pebcak (99.99% it is a pebcak 😣).

I am trying to change the margin pages based on left and right, but it doesn't work they way I expect:

```xml
    <Pagetype name="allpages" test="true()">

        <!-- SWITCH CASE MARGINS  -->

        <Switch>
            <Case test="sd:even(sd:current-page())">
                <Margin left="15mm" right="20mm" top="20mm" bottom="20mm" />
            </Case>
            <Otherwise>
                <Margin left="20mm" right="15mm" top="20mm" bottom="20mm" />
            </Otherwise>
        </Switch>
```

Sure I can create two page types, but at this point this would come handy, but perhaps it can't work with margins.

Thanks 🙏

**Comment by pgundlach** [comment]
This is not implemented in the speedata Publisher, I am afraid. It could be implemented though.... Currently it is just a static evaluation, and there is no "current page" when the page type is defined.

**Comment by Cicorione** [comment]
I see, this is not a big deal, I am going to prepare two layout then, thanks as usual for you help! 🙏

p.s. anyway implementing wouldn't be a bad thing.
