### ISSUE TITLE
`_lastpage` showing as 1 in latest stable 

### ISSUE THREAD

**Issue by grigorem** [speedata/publisher#561]
I recently updated to version 4.16.0 and noticed that `_lastpage` is not working anymore.
Version 4.14.0 seems to be working correctly, getting the right `_lastpage` value.

I normally use `runs=2` in the config file, but I also tested it as a command line argument. Same result.

I can still see the `<lastpage>` set correctly in the `publisher-aux.xml` while the PDF is showing 1, and from the log I see it is run twice.

Has anything changed regarding this or it's unexpected behaviour?

Thank you! 🙇‍♂️

**Comment by pgundlach** [comment]
I can confirm that there is a problem with `$_lastpage`. ~The aux file always has `<lastpage page='1' />` which seems to contradict your observation.~ Now that I have a two page example, I see that the last page entry in the aux file is correct. 

Thank you very much for the report!

**Comment by pgundlach** [comment]
I have updated the stable and the unstable downloads. Thanks again for the report!
