### ISSUE TITLE
four useful printing features from the PDF spec

### ISSUE THREAD

**Issue by ousia** [speedata/publisher#57]
@pgundlach, there are four useful printing features from the [PDF spec](https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=364). I think it may be worth implemented them.

* `/PrintScaling`: it only allows two values: `/AppDefault` and `/None`.

    Since its default value is `/AppDefault`, `/None` is the value to be implemented for selection.

* `/Duplex`: allows three values: `/Simplex`, `/DuplexFlipShortEdge` and `/DuplexFlipLongEdge`.

    * `/Simplex` disables duplex printing (important when printer’s default is double-sided printing).

    * `/DuplexFlipShortEdge` enforces duplex printing, flipping the short edge (for landscape layouts).

    * `/DuplexFlipLongEdge` enforces duplex printing for portrait layouts.

* `/PickTrayByPDFSize`: with values `true` or `false`.

    Besides picking the right paper tray, it selects page size from PDF document page size.

* `/NumCopies`: integer value.

    Important when you want (others) to print more than one copy from a given document.

Syntax in publisher might be:

```
<printing scale="none" duplex="single" traybypdf="yes" numcopies="50" />
```

The other two values for the `duplex` attribute would be: `portrait` and `landscape`.

What do you think of implementing these features in publisher?

**Comment by pgundlach** [comment]
Interesting, I'll take a look into it and try to find out, how much work it is.

**Comment by ousia** [comment]
@pgundlach, would these printing features be included in publisher?

**Comment by pgundlach** [comment]
Which PDF viewers honor these settings? For example, I've tried to set NumCopies to a value > 1, but neither Acrobat nor Skim (Mac) have set that as a preference.

**Comment by ousia** [comment]
> Which PDF viewers honor these settings? For example, I've tried to set NumCopies to a value > 1, but neither Acrobat nor Skim (Mac) have set that as a preference.

Acrobat should honor them. Which version of Acrobat do you use?

I haven’t tested them all, but `/Duplex` and `/PrintScaling` (set to `None`) work fine in Acrobat for Windows (from version 9).

I’m going to test `/NumCopies` and report here.

**Comment by pgundlach** [comment]
It looks like Acrobat Reader DC 2015 ignores the NumCopies field.

**Comment by ousia** [comment]
>`/NumCopies`
It looks like Acrobat Reader DC 2015 ignores the NumCopies field.

@pgundlach, could you test this with the attached file (![numcopies](https://cloud.githubusercontent.com/assets/203767/9175691/5e771012-3f87-11e5-9c79-f17be9ccf432.png))?

BTW, the file is actually a PDF file uploaded as a PNG file, so you have to download and rename it to `*.pdf`.

This file is confirmed to work. The file you sent me in private doesn’t work (I didn’t have time to inspect it).

> `/Duplex` doesn't seem to have any effect in Acrobat Reader DC 2015 (and other PDF viewers that I've tested).

Could you test this file (![a-2up](https://cloud.githubusercontent.com/assets/203767/9175980/e46e8b54-3f88-11e5-8e01-1f74142adc0e.png))?

Again it’s a PDF file renamed as PNG file.

I haven’t tested this particular file, but I have printed dozens of these files generated with ConTeXt. It is confirmed to work.

**Comment by ousia** [comment]
@pgundlach, your file with `/NumCopies` includes:

> `<< /Type /Catalog /Pages 3 0 R /ViewerPreferences << /NumCopies 123>>>>`

Would it be possible that the value could be outside the valid range in Acrobat Reader printing dialog?

It is only a guess, but the maximum value may be 99 ([_Luftballons_](https://www.youtube.com/watch?v=La4Dcd1aUcE) :smile:).

**Comment by pgundlach** [comment]
I've tried with a smaller value, but didn't work....

**Comment by ousia** [comment]
And did it work with the first attached file?

**Comment by pgundlach** [comment]
The first one seems to work fine. I'll inspect. (But due to summer holidays, it might take some time).

**Comment by pgundlach** [comment]
At most five copies can be set with Adobe Acrobat Reader.

**Comment by ousia** [comment]
> The first one seems to work fine. I'll inspect. (But due to summer holidays, it might take some time).

I understand that this is vacation time. I’m not in a hurry.

BTW, has was second attached file printed double sided?

> At most five copies can be set with Adobe Acrobat Reader. 

Did you test that on Windows or MacOSX? (I could test it on Windows.)

**Comment by pgundlach** [comment]
I've tested it on Mac (but the spec tells me that 5 is the largest integer supported). 

The second file: I have no idea how to test it on the mac. I don't understand the printing dialog, which gives me no choice of duplex printing at all even on a printer that can print both sides.

**Comment by ousia** [comment]
What I read about `/NumCopies` in the [PDF specification](https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=365) is:

> (Optional; PDF 1.7) The number of copies that shall be printed
when the print dialog is opened for this file. Values outside this
range shall be ignored.
>
>Default value: as defined by the conforming reader, but typically 1

On the second file: just open it, and print it (only select the the duplex printer, if it isn’t the default printer).

If you had to select the duplex printing, specifying `/Duplex` would be useless.

**Comment by ousia** [comment]
@pgundlach, sorry for the delayed reply.

I have asked about the accepted value for `/NumCopies` to an Adobe engineer and he confirmed what you told me: only five copies are accepted to prevent malicious documents causing trouble to users.

For my needs, up to five is a good way to specify the number of copies I need from some documents generated with Publisher.

Since the four printing keys work with Adobe, are you interested in implementing them in Pulblisher?

**Comment by pgundlach** [comment]
I will start implementing this feature. Probably not with `<Options>` but with `<PDFOptions>` or similar to separate functionality.

**Comment by ousia** [comment]
Many thanks for the implementation. `<PDFOptions>` (or even `<PrintingOptions>`) makes more as an element.

**Comment by pgundlach** [comment]
Next version will have <PDFOptions> and implements /NumCopies. I will have a look at /PickTrayByPDFSize and /PrintScaling, but I guess I cannot check /Duplex

**Comment by ousia** [comment]
Many thanks for commit 4f70643becec82cbe89954cb92ce1f3721c252cf.

I think I read somewhere that duplex printing isn’t available for Acrobat (at least) in MacOSX. But I cannot recall where I got this information from.

**Comment by pgundlach** [comment]
/Duplex is not implemented, as I cannot find any software that supports it. PrintScaling and PickTrayByPDFsize will be in 2.3.46

**Comment by ousia** [comment]
@pgundlach, many thanks for your implementation.

I only have a further question about `/Duplex`: could you reopen the issue?

I have asked in the Spanish TeX mailing list about duplex printing on MacOS X and it seems that Acrobat XI for MacOS X achieves duplex printing.

There is also a way to test this in MacOS X: the document advanced properties dialog.

Here you have two screenshots. For `/DuplexFlipLongEdge`:

<img width="350" alt="duplex-fliplong" src="https://cloud.githubusercontent.com/assets/203767/11993242/053537e6-aa2f-11e5-8a1b-69912f7b8e91.png">

And for `/DuplexFlipShortEdge`:

<img width="350" alt="duplex-flipshort" src="https://cloud.githubusercontent.com/assets/203767/11993241/052e1e20-aa2f-11e5-8948-0bb7d17af7a3.png">

Sorry, but this Adobe version is in Spanish. The weird thing is that duplex mode specifies horizontal mode when flipping long edge and vertical mode when flipping short edge. Although both documents are printed right.

At least, this is a way of checking it without having to print anything.

**Comment by ousia** [comment]
@pgundlach, many thanks for reopening the issue.

Could you provide screenshots of the advanced document properties dialog in the latest Acrobat Pro version you have for [this document](http://www.ousia.tk/duplex-portrait.pdf) and [this other one](http://www.ousia.tk/duplex-landscape.pdf)?

The screenshots I attached were taken from Acrobat XI for MacOS X.

**Comment by pgundlach** [comment]
Duplex portrait:

![duplex-portrait](https://cloud.githubusercontent.com/assets/209434/12230087/1167cab0-b84e-11e5-81c5-6d6798d9244f.png)

Duplex landscape:
![duplex-landscape](https://cloud.githubusercontent.com/assets/209434/12230093/15fcbfb8-b84e-11e5-9396-59e032e86648.png)

Thanks for the pointer, now I can implement and test it.

**Comment by pgundlach** [comment]
Will be in 2.3.47

**Comment by ousia** [comment]
@pgundlach, many thanks for the implementation.

**Comment by pgundlach** [comment]
Version 2.3.47 is online now: https://download.speedata.de/publisher/unstable/

**Comment by ousia** [comment]
Many thanks for your implementation.

I have just tested it and it works like a charm.
