### ISSUE TITLE
Windows libsplib broken

### ISSUE THREAD

**Issue by pgundlach** [speedata/publisher#570]
See #557 

```
C:\speedata-publisher\sw\lua\sdini.lua:14: module 'libsplib' not found:
        no field package.preload['libsplib']
        no file 'C:\speedata-publisher\sw/lua/libsplib.lua'
        no file 'C:\speedata-publisher/lib/libsplib.lua'
        no file 'C:\speedata-publisher\sw/lua/common/libsplib.lua'
        no file 'C:\speedata-publisher\share\lib/libsplib.so'
        no file 'C:\speedata-publisher\share\lib/libsplib.dll'
Total run time: 281.8818ms
exit status 1
```

**Comment by pgundlach** [comment]
The symbol `luaopen_libsplib` has not been exported, so it seems.

**Comment by pr-apes** [comment]
Just a way to subscribe to this issue.

Direct link to original report: https://github.com/speedata/publisher/issues/557#issuecomment-2019529234.

**Comment by pgundlach** [comment]
Version 4.17.21 seems to work with Windows 10 64 bit. Not that I am happy with the solution, but at least it works for me here...

**Comment by pr-apes** [comment]
Many thanks for your fast fix, @pgundlach.

I'm in a hurry and I made two automated tests (drag and drop).

One worked, the other one failed.

But the latter has a different cause (which I'll have to investigate further 😅).

Many thanks for your help.

**Comment by pr-apes** [comment]
@pgundlach,

I get this error message with a script that works fine with 4.17.0 (this error message is triggered by version 4.17.21):

```
C:\speedata-publisher\sw/lua/publisher\commands.lua:3845: attempt to call a nil value (field 'set_variable')
stack traceback:
	C:\speedata-publisher\sw/lua/publisher\commands.lua:3845: in function 'publisher.commands.setvariable'
	C:\speedata-publisher\sw/lua/publisher.lua:776: in function 'publisher.dispatch'
	C:\speedata-publisher\sw/lua/publisher.lua:1300: in function 'publisher.initialize_luatex_and_generate_pdf'
	C:\speedata-publisher\sw/lua/publisher.lua:1015: in function 'publisher.dothings'
	C:\speedata-publisher\sw/lua/publisher\spinit.lua:360: in function 'main_loop'
	C:\speedata-publisher\sw/lua/publisher\spinit.lua:371: in main chunk
	[C]: in function 'require'
	[\directlua]:1: in main chunk.
l.5 \directlua{require("publisher.spinit")}
                                         
The lua interpreter ran into a problem, so the
remainder of this lua chunk will be ignored.

C:\speedata-publisher\sw\lua\common\sd-callbacks.lua:82: bad argument #2 to 'format' (number expected, got nil).
<*> publisher.tex 
               adjuntos.xml datos_adjuntos-440341615487.xml
The lua interpreter ran into a problem, so the remainder of this lua chunk will be ignored.
```

Sorry, but I have no idea which XML code may be triggering this.

Many thanks for your help.

**Comment by pgundlach** [comment]
This looks like the issue is related to the new XPath parser. If you use `--xpath=luxor` then it should work. I'll provide a fix when I come back from vacation in a week.

**Comment by pr-apes** [comment]
Just added `xpath=luxor` to `%APPDATA%\speedata\publisher.cfg`.

It fixed the issue.

**Comment by pgundlach** [comment]
I'd like to close this issue. There is a workaround and I think I have fixed all these issues.

**Comment by pgundlach** [comment]
Please re-open if you don't agree, your feedback is very valuable!

**Comment by pr-apes** [comment]
It works perfectly fine, @pgundlach.

**Comment by pr-apes** [comment]
Many thanks for the fix.
