### ISSUE TITLE
huge output PDF file

### ISSUE THREAD

**Issue by ousia** [speedata/publisher#58]
@pgundlach, I have tried the example from `examples-en/mailmerging` with 3825 records (I just replicated the available ones.

The resulting `publisher.pdf` output was 8.4MB in size.

But compressing it with [Multivalent](http://www.vrspace.org/sdk/java/multivalent/Multivalent20060102.jar) Compress (a Java tool) I get a 95% compression:

```
 418K Mar 16 21:05 huge_publisher-o.pdf
 8.4M Mar 16 20:56 huge_publisher.pdf
```

The standard example with 230 records gets a 30% compression from Multivalent Compress:

```
367K Mar 16 21:09 publisher-o.pdf
524K Mar 16 21:09 publisher.pdf
```

I’m just wondering whether compression in Publisher PDF output could be improved.

Many thanks for your excellent software.

**Comment by pgundlach** [comment]
I can activate pdf object compression to achieve a slightly smaller file (4 instead of 5 MB), but not close to the numbers you achieve with multivalenet. I can't see any choice but to post-process the file.
