### ISSUE TITLE
[FreeBSD] zlib library version does not match - header: 1.3, library: 1.3.1

### ISSUE THREAD

**Issue by Cicorione** [speedata/publisher#589]
Hi @pgundlach 

perhaps it is a trivial change on the code or a missing package on my system.

Here is the error:
```
Run speedata publisher 4.19.10
PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)
signal: abort trap (core dumped)
Total run time: 15ms
```

Here the packages (I consider compatible with this issue) available on FreeBSD 14.1
```
lua51-lzlib-0.4.3_1            Lua bindings to the ZLib compression library
lua51-zlib-1.2_1               Simple streaming interface to zlib for the Lua Programming Language
lua52-lzlib-0.4.3_1            Lua bindings to the ZLib compression library
lzlib-1.14                     In-memory LZMA compression and decompression library
zlib-ng-2.1.6                  Fork of the zlib data compression library
```

Thanks... 🙏

**Comment by pgundlach** [comment]
I have no idea. You compile yourself, right? You get the luatex binary yourself from a TeX distribution, right? Does this work without problems (for example by running ./luatex --help or by running ./luatex --luaonly myfile.lua where myfile.lua is a simple lua file (`print("hello")` should be enough in it).

**Comment by Cicorione** [comment]
Hi Patrick, I am going to troubleshoot this in a couple of weeks... sorry... ☹️

**Comment by pgundlach** [comment]
Any news on this issue?

**Comment by Cicorione** [comment]
Hi Patrick,

this looks like has been resolved by itself, I was able to compile Publisher just a couple of weeks ago.
I'll confirm this later, thanks.

**Comment by Cicorione** [comment]
This has been solved by some FreeBSD updates.
