### ISSUE TITLE
Add prepend-xml and  extra-xml to new xpath mode

### ISSUE THREAD

**Issue by pgundlach** [speedata/publisher#597]

**Comment by pgundlach** [comment]
Since this is essentially the same as using xinclude, I am not sure that I need to support this in future versions.

**Comment by iclukas** [comment]
But then xinclude is not (easily) dynamically changeable since you can’t use variables. Or can you?

**Comment by pgundlach** [comment]
You are correct, xinclude is statically fixed, the interpretation of xinclude happens before interpretation of the layout file... I might think of something.
