### ISSUE TITLE
Group grid is leaking outside

### ISSUE THREAD

**Issue by Cicorione** [speedata/publisher#609]
Hi @pgundlach 

I've been quite but I was actually work intensively on my project.

I have noticed a behavior for the grid that I consider incorrect that I'd like to point out.

On my catalog I have enabled the default grid, which is 1x1 cm.
At a certain point I recall a group to which I dynamically change the inner grid based on parameters I pass through xml attributes.

When the group section is concluded I clear the page and I expect to get again the default grid, on the contrary if I don't re-set again the grid with `<SetGrid>` I get the last grid from the latest grid group used.

Now for what I understood a group can be compared to a container, therefore what happened inside the group is applied only within the group including the grid. Once the group section is gone I shouldn't even have the need to clear the page, however even clearing the page doesn't reset the grid; as a matter of on the next record I have to setup the grid manually.

I don't know if this behavior is expected or not, I found it inconsistent, I want just to be sure for the next time I have to handle a similar situation.

Thanks in advance! 🙏

**Comment by pgundlach** [comment]
This sounds like a bug. Do you by chance have a code snippet that shows the behaviour?

**Comment by Cicorione** [comment]
Unfortunately I have only my humongous catalog, I am gonna try to replicate it on a smaller scale! 👍

**Comment by Cicorione** [comment]
Hi @pgundlach,

I was trying to replicate the issue when I realized that I reported this issue mistakenly.

Let say I have three records

`Record 1` use default grid 1x1cm
`Record 2` use its own grid 3x3 with `<SetGrid>`

If now I want to `clear` the page, **does it affect the grid too?**

In my code it does not, as a matter of fact if I do:

`<ClearPage pagetype="alt" />`
`Record 3` inherits grid from `Record 2` unless I don't use `<SetGrid>` again!

Is this the correct behavior? 🤷‍♂️

Thanks! 🙏

**Comment by pgundlach** [comment]
I believe that SetGrid just sets the grid for the next page (unless the current page has not been created). So it is in effect until the next SetGrid. 

The effect of changing the grid during the typesetting run is not defined. So you can have luck that the right thing happens, but I would not rely on it.

**Comment by Cicorione** [comment]
So to recap: once I have invoked `SetGrid` if I want to change the grid than I have to invoke `SetGrid` again, is that correct?

Thanks... 🙏

**Comment by pgundlach** [comment]
> So to recap: once I have invoked `SetGrid` if I want to change the grid than I have to invoke `SetGrid` again, is that correct?

Correct. It can be tricky with timing. The `SetGrid` commands sets some defaults which are taken into account when creating a new page (this should be the behaviour, cannot test right now). So when you use `ClearPage` and right after that `SetGrid`, it should be okay (new page with the new grid). But if you use `ClearPage` then run a command which initialises the page (like `sd:number-of-columns()`), a following `SetGrid` has the effect on the following empty page created after the current empty page.
