### ISSUE TITLE
Preventing headline orphans 

### ISSUE THREAD

**Issue by rpaprotny** [speedata/publisher#62]
I came to the problem that I have a headline at the end of a page, and the following text on the next page. The standard prevention of orphans only works for paragraphs, but not for the whole "block".
Now I tried to get the position of the headline on the page, and if it is near the end, insert a pagebreak. But for every new block I only get the number "1" as line.
Is there any chance to get the absolute position, or prevent these orphans automatically?

**Comment by pgundlach** [comment]
You have to insert an "empty row" (`<NextRow>`) which advances the cursor to the next row column 1. Then you can query `sd:current-row()`.

Orphans are prevented only in the case when you use `<Output>` to output more than a rectangle of text.
