### ISSUE TITLE
[Documentation] Overlay link cannot be displayed

### ISSUE THREAD

**Issue by Cicorione** [speedata/publisher#634]
Hi Patrick, the image linked to this link: https://doc.speedata.de/publisher/static/img/overlay.png in this page: https://doc.speedata.de/publisher/en/commandreference/overlay/ looks like is corrupted:

```
The image “https://doc.speedata.de/publisher/static/img/overlay.png” cannot be displayed because it contains errors.
```

**Comment by pgundlach** [comment]
Thank you very much! This will be fixed in the next release. I have corrected a few more broken links.
