### ISSUE TITLE
proposal for PDF metadata information

### ISSUE THREAD

**Issue by ousia** [speedata/publisher#66]
@pgundlach, I think that metadata from generated PDF documents could be improved in two ways:

* _Creator_ should be _speedata Publisher [version number], www.speedata.de_.

* _Producer_ should be _LuajitTeX-0.79.1_.

* _ModDate_ may be removed if the has exactly the same value as _CreationDate_.

I hope it may help.

**Comment by pgundlach** [comment]
I'll have a look what I can change without changing the LuaTeX binary (which is a precompiled binary from TeXlive)

**Comment by ousia** [comment]
I guess these are the lines to be changed (from `src/lua/publisher.lua`):

``` lua
    if pdf.setinfo then
        pdf.setcatalog(catalog)
        pdf.setinfo([[ /Creator	(speedata Publisher) /Producer(speedata Publisher, www.speedata.de) ]])
    else
        pdf.catalog = catalog
        pdf.info = [[ /Creator (speedata Publisher) /Producer(speedata Publisher, www.speedata.de) ]]
    end
```

Sorry for not requesting a merge myself, but I don’t know how to include version numbers.

**Comment by pgundlach** [comment]
I don't know how to remove `/ModDate`, but everything else is implemented.

**Comment by ousia** [comment]
@pgundlach, many thanks for the implementation.
