### ISSUE TITLE
may Publisher (ever) replace TeX?

### ISSUE THREAD

**Issue by ousia** [speedata/publisher#80]
@pgundlach,

I guess the answer to my question is a negative one.

But is Publisher not intended to replace TeX (ConTeXt in my case) due to some missing features, or is there something in its design that makes this replacement impossible?

BTW, are the slides from [_Erzeugen von Dokumenten mit dem speedata Publisher_](http://www.dante.de/events/dante2016/Programm/vortraege.html#gundlachgrycmann) available anywhere?

Many thanks for your help.

**Comment by pgundlach** [comment]
Hello @ousia 
The publisher is not intended to replace TeX/LaTeX or ConTeXt. It tries to offer the user a subset of the capabilities and restrict the programming posibilities / errors. It will never be as flexible as any of the TeX macro packages (or TeX itself).

The focus is slightly different: I try to provide the building blocks to be able to generate 95% of the documents (mainly product catalogs, but also other more text containing documents) while providing an abstraction to TeX (no macro programming, user doesn't even notice that TeX is running underneath) and having an exact documentation and quality assurance mechanism. 

There are no slides from the DANTE 2016 tutorial availabe. It was an interactive tutorial with lot's of code shown.

I will close this if you don't object.

**Comment by ousia** [comment]
Many thanks for your reply, @pgundlach.

I see the point, so I’m closing the issue myself.
