### ISSUE TITLE
<AtPageShipout> doesn't properly execute on final page

### ISSUE THREAD

**Issue by AlpBilgin** [speedata/publisher#85]
Hello,

I run [this](http://pastebin.com/h1hYA0Sn) (shortened) XML template through Speedata Publisher 2.2.0 to create a quotation document. The document contains a table of variable size and I simply let table be divided across multiple pages automatically by SP. The problem is, while the header elements appear on every page, the footer of the last page does not seem to be inserted. I also receive no errors from SP. You will see towards the end of my example code, that I manually insert a copy of the footer to the end of the document.

I don't really know if this is a bug or an unintended use case, I would really like to hear your opinion about it.

**Comment by pgundlach** [comment]
This is a (nasty) bug. I'll fix it soon, thanks for the reminder.

Workaround: Insert a `<NewPage>` before the closing tag of `<Record element="quotation">`.

**Comment by AlpBilgin** [comment]
Thank you for the tip.
